src/content/reference/cli.mdx
`endpoints` should be an h3, not an h4
https://deploy-preview-82--okteto-docs.netlify.app/docs/reference/cli/#endpoints
=> Fix heading level for `endpoints`

src/content/cloud/preview-environments/gitlab.mdx, src/content/cloud/preview-environments/overview.mdx, src/content/enterprise/administration/configuration.mdx, src/content/enterprise/digitalocean.mdx, src/content/enterprise/install/releases.mdx, versioned_docs/version-0.10/cloud/preview-environments/gitlab.mdx, versioned_docs/version-0.10/cloud/preview-environments/overview.mdx, versioned_docs/version-0.10/enterprise/administration/configuration.mdx, versioned_docs/version-0.10/enterprise/digitalocean.mdx, versioned_docs/version-0.10/enterprise/install/releases.mdx
Fixing a typo in doc repo.
dt-work:okteto-docs dt$ for i in $(find . -type f | xargs grep "Gitlab" |  awk -F: '{print $1}' | uniq); do sed -e 's/Gitlab/GitLab/g' $i > $i.sed && mv $i.sed $i;  done;
Signed-off-by: David 'DT' Thomas <dt@okteto.com>
=> Renaming Gitlab > GitLab in all docs

docusaurus.config.js, src/styles/colors.scss, src/theme/Button/styles.scss
I like the aesthetic of Gitlab docs. I think is clean and less distracting.
@huguestennier would it be possible to copy their layout, and have the search on the left (so it's more obvious). And a more noticeable button for the free trial link?
=> update docs header to remove options

src/content/cloud/okteto-cli.mdx, src/styles/main.scss, src/theme/TiersList/index.js, src/theme/TiersList/styles.scss
Add the ability to show tiers badge next to headings
```js
<TiersList tiers="Starter Scale Self-host" />
```
https://deploy-preview-99--okteto-docs.netlify.app/docs/cloud/okteto-cli/#heading-2 (will remove before we merge)
=> Add Tiers badge to headings

src/content/reference/manifest.mdx
Signed-off-by: Teresa Romero <teresa@okteto.com>
Documented extended notation for dependencies at manifest 2.0 was not correct.
=> Fix the extended notation at dependencies in manifest

src/content/enterprise/eks.mdx, versioned_docs/version-0.10/enterprise/eks.mdx, versioned_docs/version-0.11/enterprise/eks.mdx
This PR adds a note discouraging the use of `CNAME` records for `*` that point to the public hostname of AWS Elastic Load Balancers.
Okteto Enterprise automatic certificate management uses cert-manager to issue the wildcard certificate used by the deployment. This certificate is issued by Let's Encrypt as default and uses ACME dns01 verification challenge, which consists of creating a `TXT` dns record for the Okteto domain.
If the user creates a `CNAME` dns record for `*`, it will shadow any other dns records, including `TXT`. This blocks the issue/renewal process as the verification can no longer be achieved.
Reasons why a user may set a `CNAME` record include the scenario where they manage DNS from a different AWS account, making it impossible to set an `A` dns record with an alias, or …
=> docs: add note regarding the use of CNAME records

src/content/cloud/okteto-pipeline.mdx, src/content/enterprise/install/releases.mdx, src/content/reference/cli.mdx, src/content/reference/manifest.mdx
When deploying a pipeline, now the file path is relative to the manifest folder
Fix https://github.com/okteto/app/issues/3901
=> Added pipeline relative path note

docusaurus.config.js
1. Go to https://deploy-preview-116--okteto-docs.netlify.app/docs/sitemap-docs.xml
2. All links should be prefixed with `www.`
=> Update sitemap to use `www` version

src/content/enterprise/install/releases.mdx
Okteto Enterprise 0.13 Release Notes. Reviewers taken from the changelog between 0.12 and 0.13. Please review in case there's something missing about your changes that should be added (or removed)
=> Okteto Enterprise 0.13.0 release notes

src/content/cloud/deploy-from-helm.mdx, src/content/enterprise/administration/configuration.mdx
We are disabling the Helm catalog by default in self-hosted installations.
Our catalog requires to install custom CRDs that make the whole installation process more complicated
=> Update docs to document that the Helm catalog is disabled by default

docusaurus.config.js
This is to make it more obvious which is the `latest` version of the docs.
=> add version to the latest doc

src/content/administration/private-repositories/ssh-key.mdx
Now we have the ability to download the SSH key from the Admin View, we shouldn't document how to access it using `kubectl`. This is too dependent on the implementation of the feature, and it's a poorer experience
=> Remove "kubectl" command to retrieve ssh key

src/content/reference/manifest.mdx
I was waiting to document `AttachTo` https://github.com/okteto/okteto/issues/2211, but its implementation is being delayed, and people using `services` is asking about why `services` sn not in the current docs
=> Document "services" field

src/theme/Image/index.js
As part of the SEO improvements tasks, add lazy loading on all images by default.
https://app.hubspot.com/content-strategy/5418301/recommendations/domain/1309617/hostname/1949392/category/PERFORMANCE/type/DEFER_LOADING_OFFSCREEN_IMAGES
=> SEO improvements - Add image lazy loading by default

src/content/cloud/okteto-cli.mdx, src/content/reference/cli.mdx
documentation on timeout handling by the client when communicating with the buildkit daemon
https://github.com/okteto/buildkit/pull/18
=> add keepalive client docs

src/content/reference/cli.mdx
`BUILDKIT_HOST` can be used to configure your own buildkit server
=> Add a comment on `BUILDKIT_HOST`

src/content/enterprise/administration/configuration.mdx
It's time to document `globalClusterRole` because it's used now by several users
=> Document cluster role supported configurations

src/content/self-hosted/aks.mdx, src/content/self-hosted/civo.mdx, src/content/self-hosted/digitalocean.mdx, src/content/self-hosted/eks.mdx, src/content/self-hosted/gke.mdx
This guide covers on-premise installations where s3-like services are not available and applications must be exposed behind an existing ingress controller, including Okteto
=> Remove requirements for publicly accessible dns domains

netlify.toml
For v1, we renamed our folders structure. Make sure we avoid broken links
These should redirect to `/self-hosted` instead of 404:
https://deploy-preview-205--okteto-docs.netlify.app/docs/enterprise/install/overview/
https://deploy-preview-205--okteto-docs.netlify.app/docs/enterprise/eks/#creating-an-iam
=> Redirect /enterprise to /self-hosted 

src/content/self-hosted/gke.mdx, src/content/self-hosted/gke/config.yaml
Recently google changed how they store the cluster endpoint in the default namespace to point to the internal cluster IP. This breaks our logic to infer the cluster public endpoint.
We have to document how to configure this value as we do for other providers
=> Document `cluster.endpoint` for GKE

versioned_docs/version-0.15/enterprise/administration/configuration.mdx
Explain tasks to be done on the oauth provider side, and make each provider linkable, so it's easier to share a link for a given oauth provider
=> Add more info about how to configure OAuth with Okteto

src/content/self-hosted/administration/configuration.mdx, versioned_docs/version-0.15/enterprise/administration/configuration.mdx
In order to set the ingress class name of ingresses created by the okteto installation, the field`ingressClassName` must be set on each ingress. USing annotations is no longer supported
=> Document ingress.oktetoIngressClass

src/content/self-hosted/aks.mdx, src/content/self-hosted/aks/config.yaml, src/content/self-hosted/civo.mdx, src/content/self-hosted/civo/config.yaml, src/content/self-hosted/digitalocean/config.yaml, src/content/self-hosted/eks.mdx, src/content/self-hosted/eks/config.yaml
This is a critical setting that should be configured from day one. Otherwise, everyone with a github account is able to login to Okteto
=> Make it clearer "organization" should be defined when using GitHub OAuth

src/content/self-hosted/aks.mdx, src/content/self-hosted/civo.mdx, src/content/self-hosted/eks.mdx, src/content/self-hosted/gke.mdx, versioned_docs/version-0.11/enterprise/aks.mdx, versioned_docs/version-0.11/enterprise/civo.mdx, versioned_docs/version-0.11/enterprise/eks.mdx, versioned_docs/version-0.11/enterprise/gke.mdx, versioned_docs/version-0.12/enterprise/aks.mdx, versioned_docs/version-0.12/enterprise/civo.mdx, versioned_docs/version-0.12/enterprise/eks.mdx, versioned_docs/version-0.12/enterprise/gke.mdx, versioned_docs/version-0.13/enterprise/aks.mdx, versioned_docs/version-0.13/enterprise/civo.mdx, versioned_docs/version-0.13/enterprise/eks.mdx, versioned_docs/version-0.13/enterprise/gke.mdx, versioned_docs/version-0.14/enterprise/aks.mdx, versioned_docs/version-0.14/enterprise/civo.mdx, versioned_docs/version-0.14/enterprise/eks.mdx, versioned_docs/version-0.14/enterprise/gke.mdx, versioned_docs/version-1.0/self-hosted/aks.mdx, versioned_docs/version-1.0/self-hosted/civo.mdx, versioned_docs/version-1.0/self-hosted/eks.mdx, versioned_docs/version-1.0/self-hosted/gke.mdx
Docusaurus adds a trailing slash by default to all links for better SEO with the [trailingSlash config](https://docusaurus.io/docs/api/docusaurus-config#trailingSlash).
Problem: It also adds a trailing slash to links that shouldn’t have them like `.yaml` files.
Solution: Use full URLs instead of relative URLs to avoid Docusaurus transformation.
=> Use full URL instead of relative URL for config files

src/content/reference/cli.mdx
Signed-off-by: Pablo Chico de Guzman <pchico83@gmail.com>
`okteto build` can be used without an okteto manifest. This is useful when you want to build dynamic images not defined in your okteto manifest.
=> Add a note about how to use "okteto build" without an okteto manifest

src/content/cloud/registry.mdx
=> add docs about push helm chart into okteto registry

src/content/self-hosted/administration/github.mdx, versioned_docs/version-0.11/enterprise/administration/private-repositories/github-application.mdx, versioned_docs/version-0.12/enterprise/administration/private-repositories/github-application.mdx, versioned_docs/version-0.13/enterprise/administration/github.mdx, versioned_docs/version-0.14/enterprise/administration/github.mdx, versioned_docs/version-0.15/enterprise/administration/github.mdx, versioned_docs/version-1.0/self-hosted/administration/github.mdx
Fix the broken image URL at the bottom of the page
1. Visit https://deploy-preview-235--okteto-docs.netlify.app/docs/self-hosted/administration/github/#verifying-your-installation and the image should display correctly
=> Fix broken image on GitHub Integration

sidebars.js, src/content/cloud/volume-snapshots.mdx, src/content/self-hosted/administration/volume-snapshots.mdx
After helping a few users to configure volume snapshots, I have done several changes to the docs to make this feature more discoverable.
- Add a section under `Development Environments` explaining how to use this feature from a developer's point of view. This feature is available in Cloud and SaaS by default.
- Add a sample for Compose.
- Keep the doc under `Self-Hosted/Configuration` just with the configuration steps to enable this feature in Self-Hosted.
=> A general pass to the volume snapshots feature

src/content/samples/python.mdx
PR already merged in the sample repo:
https://github.com/okteto/python-getting-started/pull/12
=> Enable flask development mode on `okteto up`

src/content/cloud/private-endpoints.mdx, versioned_docs/version-0.11/cloud/private-endpoints.mdx, versioned_docs/version-0.12/cloud/private-endpoints.mdx, versioned_docs/version-0.13/cloud/private-endpoints.mdx, versioned_docs/version-0.14/cloud/private-endpoints.mdx, versioned_docs/version-0.15/cloud/private-endpoints.mdx, versioned_docs/version-1.0/cloud/private-endpoints.mdx, versioned_docs/version-1.1/cloud/private-endpoints.mdx
Use a image instead of a build since we don't have a `Dockerfile` defined or repo linked
Replace `port` into `ports`
=> fix: private endpoints compose examples

src/content/reference/docker-compose.mdx
Adds documentation about `x-okteto-readiness` and `x-okteto-liveness`
=> docs: add healthcheck docs about x-okteto healthchecks

src/content/samples/php.mdx, versioned_docs/version-0.13/samples/php.mdx, versioned_docs/version-0.14/samples/php.mdx, versioned_docs/version-0.15/samples/php.mdx, versioned_docs/version-1.0/samples/php.mdx, versioned_docs/version-1.1/samples/php.mdx, versioned_docs/version-1.2/samples/php.mdx
We need to update PHP server start messages to use PHP 8 instead of PHP 7
=> Change messages to use php 8

src/content/cloud/preview-environments/overview.mdx
As reported here: https://okteto.slack.com/archives/C02SX9665RP/p1673533384864009
=> Fix wrong Okteto Cloud docs link

src/content/reference/manifest.mdx, versioned_docs/version-1.2/reference/manifest.mdx, versioned_docs/version-1.3/reference/manifest.mdx
`build_args` is referred in the sample, but the right field name is `args`
=> Fix "build_args" docs

src/content/reference/cli.mdx
Reference pr: https://github.com/okteto/okteto/pull/3215. I also changed the position of the `--env` flag to match the [`up.go`](https://github.com/okteto/okteto/blob/master/cmd/up/up.go#L366) file 
Signed-off-by: Abhisman Sarkar <abhisman.sarkar@gmail.com>
=> Added documentation for the `--command` flag

src/content/reference/docker-compose.mdx
Adds documentation about the update policy annotation on compose
=> docs: add documentation about update policy annotation

src/content/reference/cli.mdx
Release https://github.com/okteto/okteto/releases/tag/2.11.0 introduced the flag `--all` into the command `okteto destroy` in order to delete all the resources that are present at the current namespace.
Also, `okteto preview destroy` and `okteto namespace destroy` now execute the commands that are defined under the `destroy` section of the okteto manifest.
=> Added destroy flag and info to namespace and preview destroy

src/content/self-hosted/administration/configuration.mdx, src/content/self-hosted/install/releases.mdx, versioned_docs/version-1.4/self-hosted/administration/configuration.mdx, versioned_docs/version-1.4/self-hosted/install/releases.mdx
Virtual services moved from `unsupported.virtualServices.enabled` to `virtualServices.enabled`
=> Document virtual services

netlify.toml
Fix https://github.com/okteto/docs/issues/289
We should be able to link to https://www.okteto.com/docs/xxx/ and it redirects to https://www.okteto.com/docs/xxx/welcome/overview
These should all work:
https://deploy-preview-296--okteto-docs.netlify.app/docs/0.11
https://deploy-preview-296--okteto-docs.netlify.app/docs/0.12
https://deploy-preview-296--okteto-docs.netlify.app/docs/0.13
https://deploy-preview-296--okteto-docs.netlify.app/docs/0.14
https://deploy-preview-296--okteto-docs.netlify.app/docs/0.15
https://deploy-preview-296--okteto-docs.netlify.app/docs/1.1
https://deploy-preview-296--okteto-docs.netlify.app/docs/1.2
https://deploy-preview-296--okteto-docs.netlify.app/docs/1.3
https://deploy-preview-296--okteto-docs.netlify.app/docs/1.4
=> Add redirect for versions home page

src/content/self-hosted/eks.mdx, src/content/self-hosted/install/releases.mdx, versioned_docs/version-0.13/enterprise/eks.mdx, versioned_docs/version-0.14/enterprise/eks.mdx, versioned_docs/version-0.15/enterprise/eks.mdx, versioned_docs/version-1.0/self-hosted/eks.mdx, versioned_docs/version-1.1/self-hosted/eks.mdx, versioned_docs/version-1.2/self-hosted/eks.mdx, versioned_docs/version-1.3/self-hosted/eks.mdx, versioned_docs/version-1.4/self-hosted/eks.mdx
The guide to configuring the Registry with IAM Users is confusing. It mentions IAM Roles, but we are not using roles
=> Make it clear how to configure the registry in AWS with IAM Users

src/content/cloud/volume-snapshots.mdx, src/content/self-hosted/administration/volume-snapshots.mdx
Updating the guides to reflect the following changes:
- Move from `v1beta1` version to `v1`
- Use the storage class `csi-okteto` in SaaS samples. We don't expose `standard` vs `ssd` options anymore
- From the admin guide, link to the dev guide. The dev sample in the admin guide was incomplete
=> Update volume snapshot guides

src/content/self-hosted/administration/certificates.mdx
Adding links to our community blog posts for aws managed certificates and godaddy to improve the discoverability of this guides
=> Add links to community guides for aws manages certificates and godaddy

src/content/self-hosted/administration/configuration.mdx, versioned_docs/version-1.5/self-hosted/administration/configuration.mdx
Several customers are asking about the tasks done by our daemonset on every node.
I document it in a single place, when talking abouf the daemonset. I also added a reference to tolerations, because they can be used to limit the scope of the nodes where the daemonset is deployed
=> Document the tasks done by daemonset on each node

src/content/administration/dashboard.mdx
Although `dst` keeps working, docker/buildkit updated the docs to use `target`:
https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md#run---mounttypesecret
=> Update mount secrets to use "target" instead of "dst"

src/content/cloud/okteto-cli.mdx, versioned_docs/version-0.11/cloud/okteto-cli.mdx, versioned_docs/version-0.12/cloud/okteto-cli.mdx, versioned_docs/version-0.13/cloud/okteto-cli.mdx, versioned_docs/version-0.14/cloud/okteto-cli.mdx, versioned_docs/version-0.15/cloud/okteto-cli.mdx, versioned_docs/version-1.0/cloud/okteto-cli.mdx, versioned_docs/version-1.1/cloud/okteto-cli.mdx, versioned_docs/version-1.2/cloud/okteto-cli.mdx, versioned_docs/version-1.3/cloud/okteto-cli.mdx, versioned_docs/version-1.4/cloud/okteto-cli.mdx
[Okteto Manifests](https://www.okteto.com/docs/cloud/okteto-cli/#okteto-manifest) section misses a minor code snippet in the following line:
_This example shows how to `build` the container image of the api microservice, how to `deploy` the application using its helm chart, and how to `dev`elop on the api microservice by synchronizing the local filesystem on the container path `/usr/src/app`._
Notice the use of `dev`elop. It should be `develop`.
=> Fixes minor missing code snippet in all version

src/content/self-hosted/administration/configuration.mdx
Chart 1.6.0 comes with the ability to define quotas for max services, load balancers and node ports
=> Add docs for maxServices, maxLoadBalancers and maxNodePorts

src/styles/main.scss
Make sure the search input doesn’t overlap the "Get Free Trial" CTA in the header
=> Fix search input overlapping CTA

src/content/self-hosted/aks.mdx, src/content/self-hosted/digitalocean.mdx, src/content/self-hosted/eks.mdx, src/content/self-hosted/gke.mdx, src/content/self-hosted/install/preparation.mdx, src/content/self-hosted/install/releases.mdx, src/content/self-hosted/offline.mdx
Release notes for `1.6`
There is a couple of things left:
* Documentation for 2 features: The default ingress class we have changed in `1.6` and the public override public availability and the changes related to the private endpoints handler. @jpf-okteto is working on them. The idea would be to include a link to those documents in the corresponding feature point
* CVE fixes included in the release. There were several but I'm not sure which ones. @jpf-okteto once you finish the other documentation tasks, can you include those points in the release notes?
=> Release notes for release 1.6

src/content/cloud/ssl.mdx, src/content/self-hosted/install/releases.mdx
Document the annotation `dev.okteto.com/endpoints` coming in 1.7.0.
Also document the annotation `dev.okteto.com/hide-from-ui: true`, that it's already supported was it wasn't documented before.
=> Document annotations to customize the endpoints shown in the Okteto UI

src/content/self-hosted/administration/configuration.mdx, src/content/self-hosted/aks.mdx, src/content/self-hosted/eks.mdx, src/content/self-hosted/gke.mdx, src/content/self-hosted/offline.mdx
Add more explanations about the meaning of the `subdomain` field and how to use it to configure your wildcard subdomain.
I also added a small section explaining how to diable the installation of the nginx ingress controller.
=> Improve the documentation of the "subdomain" field

src/content/self-hosted/administration/configuration.mdx, src/content/self-hosted/aks.mdx, src/content/self-hosted/aks/config.yaml, src/content/self-hosted/civo.mdx, src/content/self-hosted/civo/config.yaml, src/content/self-hosted/digitalocean.mdx, src/content/self-hosted/digitalocean/config.yaml, src/content/self-hosted/eks.mdx, src/content/self-hosted/eks/config.yaml, src/content/self-hosted/gke.mdx, src/content/self-hosted/gke/config.yaml, src/content/self-hosted/install/releases.mdx, src/content/self-hosted/offline.mdx
The default installation for buildkit won't use a PVC anymore. The PVC must be enabled explicitly.
This PR covers the following changes related to buildkit:
- Document the new buildkit fields
- Update our cloud provider guides to enable buildkit persistance
- Update the release notes
**Note**: this isn't a breaking change. Existing installation will keep using the existing PVC
@maroshii @teresaromero mention you to approve the tech docs since you have worked on this
=> Update documentation for buildkit

netlify.toml
Redirects `/` to `/docs` so if you try to access the deploy preview URL, you won’t see a 404
https://deploy-preview-349--okteto-docs.netlify.app/ should redirect to https://deploy-preview-349--okteto-docs.netlify.app/docs
=> Add root path redirect

src/content/getting-started.mdx, versioned_docs/version-0.11/getting-started.mdx, versioned_docs/version-0.12/getting-started.mdx, versioned_docs/version-0.13/getting-started.mdx, versioned_docs/version-0.14/getting-started.mdx, versioned_docs/version-0.15/getting-started.mdx, versioned_docs/version-1.0/getting-started.mdx, versioned_docs/version-1.1/getting-started.mdx, versioned_docs/version-1.2/getting-started.mdx, versioned_docs/version-1.3/getting-started.mdx, versioned_docs/version-1.4/getting-started.mdx, versioned_docs/version-1.5/getting-started.mdx
Download link in windows was pointing to previous release process. Now the user should write what is the channel he wants to download it from.
Fixes https://github.com/okteto/okteto/issues/3562
=> fix: download link windows

src/content/self-hosted/administration/configuration.mdx, src/content/self-hosted/aks.mdx, src/content/self-hosted/aks/config.yaml, src/content/self-hosted/civo.mdx, src/content/self-hosted/civo/config.yaml, src/content/self-hosted/digitalocean.mdx, src/content/self-hosted/digitalocean/config.yaml, src/content/self-hosted/digitalocean/marketplace.md, src/content/self-hosted/eks.mdx, src/content/self-hosted/eks/config.yaml, src/content/self-hosted/gke.mdx, src/content/self-hosted/gke/config.yaml, src/content/self-hosted/install/deployment.mdx, src/content/self-hosted/offline.mdx
The `email` field is no longer needed, and by removing it, we simplify our installation guides
=> Remove "email" from helm values file, it's comes from the "license"

src/content/self-hosted/aks.mdx, src/content/self-hosted/digitalocean.mdx, src/content/self-hosted/eks.mdx, src/content/self-hosted/gke.mdx, src/content/self-hosted/install/preparation.mdx, src/content/self-hosted/install/releases.mdx
We are supporting 1.25 for release 1.8.
- Update versions at self-hosted installation guides
- Added info at release notes for new version support and deprecation notice
=> Support kubernetes 1.25

src/content/self-hosted/install/releases.mdx, src/content/self-hosted/install/upgrade.mdx
Document clean upgrade to Kubernetes 1.25 by disabling pod security policies first
=> Document upgrade to Kubernetes 1.25 process

src/content/getting-started.mdx
Turns out scoop hand `hold` your package and will tell you it's upgraded even though it's not
=> Add caveat for scoop upgrades

src/content/reference/manifest.mdx
Add replicas field in Services to specify the required replicas for services.
[https://github.com/okteto/okteto/pull/3556](https://github.com/okteto/okteto/pull/3556)
=> Add replicas field in Services field

src/content/self-hosted/install/upgrade.mdx, versioned_docs/version-1.7/self-hosted/install/upgrade.mdx, versioned_docs/version-1.8/self-hosted/install/upgrade.mdx
Added a paragraph in the `Before Upgrade` section to recommend to set explicitly the persistence for BuildKit before upgrading to `1.7`. Updated also `1.7` and `1.8` versions
=> Added a paragraph to recommend users to set explicitly the setting buildkit.persistence.enabled: true before upgrading to 1.7

src/content/self-hosted/administration/configuration.mdx, src/content/self-hosted/aks.mdx, src/content/self-hosted/aks/config.yaml, src/content/self-hosted/digitalocean.mdx, src/content/self-hosted/digitalocean/config.yaml, src/content/self-hosted/eks.mdx, src/content/self-hosted/eks/config.yaml, src/content/self-hosted/gke.mdx, src/content/self-hosted/gke/config.yaml, src/content/self-hosted/offline.mdx
We are recommending to use buildkit within the ingress so this PR removes the documented installation and config.yaml properties for buildkit setting as LoadBalancer
=> Remove buildkit LoadBalancer config

src/content/reference/docker-compose.mdx
`x-node-selector` translates to Kubernetes node selectors
=> Document "x-node-selector" in the compose docs

src/content/self-hosted/administration/github.mdx, versioned_docs/version-1.3/self-hosted/administration/github.mdx, versioned_docs/version-1.4/self-hosted/administration/github.mdx, versioned_docs/version-1.5/self-hosted/administration/github.mdx, versioned_docs/version-1.6/self-hosted/administration/github.mdx, versioned_docs/version-1.7/self-hosted/administration/github.mdx, versioned_docs/version-1.8/self-hosted/administration/github.mdx, versioned_docs/version-1.9/self-hosted/administration/github.mdx
Adding that query parameter to the GitHub App auth callback makes that we display the following screen instead of a blank page when users end configuring the repositories accessible by the GitHub App
=> Added ?origin=github to GitHub App auth callback 

README.md
The image for the contributors that are supposed to be [here](https://github.com/okteto/docs#contributors) is not present due to the unavailability of the link. 
This PR adds the correct link.
=> Update README.md to display contributor images

src/content/self-hosted/administration/configuration.mdx, versioned_docs/version-1.7/self-hosted/administration/configuration.mdx, versioned_docs/version-1.8/self-hosted/administration/configuration.mdx, versioned_docs/version-1.9/self-hosted/administration/configuration.mdx
The secret name should be `key` because that's what is expected by the pods. cc @rberrelleza
=> changing name of key for external storage configuration docs

src/content/self-hosted/aks.mdx, src/content/self-hosted/aks/config.yaml, src/content/self-hosted/civo.mdx, src/content/self-hosted/civo/config.yaml, src/content/self-hosted/digitalocean.mdx, src/content/self-hosted/digitalocean/config.yaml, src/content/self-hosted/eks.mdx, src/content/self-hosted/eks/config.yaml, src/content/self-hosted/gke.mdx, src/content/self-hosted/gke/config.yaml, src/content/self-hosted/install/config.yaml, src/content/self-hosted/install/deployment.mdx, src/content/self-hosted/offline.mdx
Okteto chart 1.10 removes the need to specify `cluster.endpoint` in the Helm values file.
This PR updates the installation guides to remove this dependency
=> Remove dependency on "cluster.endpoint" to install the okteto chart

docusaurus.config.js
To incentivize users to contribute to the docs
With https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#editUrl and the edit URL for github https://github.com/okteto/docs/edit/main
I've tested multiple versions and all work well:
- oldest 1.4
- current 1.10
- next 1.11
=> Add "Edit this page" button to all pages

okteto.yml, src/content/reference/cli.mdx
This PR mentions the `--output` flag for the `okteto preview list` command that was added in [this PR](https://github.com/okteto/okteto/pull/3804)
=> New supported flag for okteto preview list

src/content/self-hosted/aks.mdx, src/content/self-hosted/aks/config.yaml, src/content/self-hosted/civo.mdx, src/content/self-hosted/civo/config.yaml, src/content/self-hosted/digitalocean.mdx, src/content/self-hosted/digitalocean/config.yaml, src/content/self-hosted/eks.mdx, src/content/self-hosted/eks/config.yaml, src/content/self-hosted/gke.mdx, src/content/self-hosted/gke/config.yaml, src/content/self-hosted/install/config.yaml, src/content/self-hosted/install/deployment.mdx, src/content/self-hosted/install/preparation.mdx, src/content/self-hosted/offline.mdx
We detected an scenario in which the Kubernetes API exposed behind our ingress is not working correctly when there are self-signed certificates, so we have to restore again the requirement of configuring the `cluster.endpoint` property until we fix it
This is a revert of commits 8387d26 and b08a6b9
=> Revert changes in public guides to explain again how to configure the cluster endpoint in the cart configuration

netlify.toml
Redirects old version to the current docs path
https://deploy-preview-457--okteto-docs.netlify.app/docs/0.12/enterprise/install/deployment/ should redirect to https://deploy-preview-457--okteto-docs.netlify.app/docs/self-hosted/install/deployment/
=> Add redirects for enterprise => self-hosted

src/content/reference/cli.mdx
Added a comment in the flag `--remote` of deploy and destroy commands to indicate that Okteto uses your local SSH agent to clone private repositories when working remotely. Probably we should have a dedicated section for the remote execution but for now, I added it here
=> Added documentation about SSH in the --remote flag of deploy and destroy commands

src/content/self-hosted/administration/configuration.mdx
Added documentation for a new config setting which allow admins to change the expiration time of tokens used in Kubernetes credentials generated by Okteto.
Added a note to indicate that the maximum expiration might be limited by the Kubernetes server.
=> Document new helm chart setting for kubetokens expiration

src/content/self-hosted/eks.mdx, versioned_docs/version-1.12/self-hosted/eks.mdx
In the configuration file we offer to download directly from the docs (https://github.com/okteto/docs/blob/main/src/content/self-hosted/eks/config.yaml) we include the settings to configure an NLB, but the snippet in the page doesn't have it, so as NLB is preferred, I'm adding also those settings in the snippet in case users copy-paste directly from there instead of downloading the config example file
=> Added configuration settings to configure NLB for Okteto in default installation guide for EKS

src/content/reference/manifest.mdx
I was doing a session with a user to use `--remote` and I found a few typos.
Also, I reorder a sentence to make it flow better
=> Fix a few typos in the deploy/destroy section for "--remote"

src/content/self-hosted/install/releases.mdx, versioned_docs/version-1.13/self-hosted/install/releases.mdx
Even if the phrase about supported Kubernetes versions was in a new line, it wasn't rendered corretly
=> Added a blank line between date and supported version. It wasn't being rendered properly

src/content/reference/cli.mdx
documentation about new flags and subcommands to support labels for dev environments.
Changes are:
- new flag `--label` in `okteto pipeline deploy` command
- new flag `--reuse-params` in `okteto pipeline deploy` command
- new command `list` for `okteto pipeline`
- flags supported in `okteto pipeline list` command
=> add labels in dev environments docs

src/content/self-hosted/administration/configuration.mdx
The quotas section has been updated with the defaults copied directly from the latest chart and missing descriptions have been added.
=> Updating quota section in self-hosted configuration docs.

src/content/reference/cli.mdx
Updates the docs for `okteto context show` which has a new flag called `--include-token` (see related [PR](https://github.com/okteto/okteto/pull/4010))
| Before | After |
|--------|-------|
|    <img src="https://github.com/okteto/docs/assets/2318450/e76c325c-f78f-44df-9137-fb0a60dceea7" width="300" height="auto" alt="before" />    |     <img src="https://github.com/okteto/docs/assets/2318450/9ef71340-8810-4aa2-9c96-78f844eadeff" width="300" height="auto" alt="after" />  |
=> docs: add cmd flags to `context show`

src/content/self-hosted/install/releases.mdx, src/content/self-hosted/install/upgrade.mdx
As part of `1.15.x` release, we will enable [chroot mode](https://kubernetes.io/blog/2022/04/28/ingress-nginx-1-2-0/) by default in our ingress controllers.
This PR adds a call out to it letting customers know that it implies to include a new capability to controller pods and it has to be available. It also indicates how to disable it in case they are not interested on it
=> Added documentation for 1.15.x release indicating the change we did to enable chroot by default

src/content/self-hosted/administration/configuration.mdx, versioned_docs/version-1.14/self-hosted/administration/configuration.mdx, versioned_docs/version-1.15/self-hosted/administration/configuration.mdx
The default is `bearer` as per https://artifacthub.io/packages/helm/okteto/okteto?modal=values&path=insights
=> Fix default

src/content/get-started/deploy-first-env.mdx, versioned_docs/version-1.10/using-dev-envs.mdx, versioned_docs/version-1.11/using-dev-envs.mdx, versioned_docs/version-1.12/using-dev-envs.mdx, versioned_docs/version-1.13/using-dev-envs.mdx, versioned_docs/version-1.14/using-dev-envs.mdx, versioned_docs/version-1.15/using-dev-envs.mdx, versioned_docs/version-1.4/using-dev-envs.mdx, versioned_docs/version-1.5/using-dev-envs.mdx, versioned_docs/version-1.6/using-dev-envs.mdx, versioned_docs/version-1.7/using-dev-envs.mdx, versioned_docs/version-1.8/using-dev-envs.mdx, versioned_docs/version-1.9/using-dev-envs.mdx
In https://github.com/okteto/docs/pull/558, we moved all the images into the `assets` folder - it looks like I missed one page
=> Fix broken images

src/content/get-started/cloud-provider-guides/aks.mdx, src/content/get-started/cloud-provider-guides/civo.mdx, src/content/get-started/cloud-provider-guides/digitalocean.mdx, src/content/get-started/cloud-provider-guides/eks.mdx, src/content/get-started/cloud-provider-guides/gke.mdx
This PR removes mentions of sample `config.yaml` files since they are outdated/not maintained currently.
It rewords these sections and adds a reference link to the `Okteto helm values` reference page for further reading.
=> Removing and rewording outdated config examples.

src/content/get-started/cloud-provider-guides/eks.mdx, src/content/self-hosted/eks/config.yaml
Add a step to the EKS SH install guide to add the Amazon EBS CLI storage driver add-on
=> Add storage driver requirements to EKS install guide

src/content/get-started/deploy-first-env.mdx, src/content/get-started/install-okteto-cli.mdx, versioned_docs/version-1.15/getting-started.mdx, versioned_docs/version-1.15/using-dev-envs.mdx
A few minor corrections to improve legibility of the getting started section plus a couple of comments below:
Beyond these changes there's something that puzzles me a bit about the [Movies App with Helm](https://www.okteto.com/docs/using-dev-envs/) section. I think it's a bit of a stretch to assume that the reader understands why the Helm option includes an Okteto Manifest. Basically my problem is with the first sentence in that section: "Since we already have an Okteto Manifest".
Also note the result of `okteto up` that I got, since it said that no endpoints were available while in the ui they were clearly there.
=> Typos in the getting started tutorial

src/content/preview/using-gitlab-cicd.mdx
- Remove mentions to Okteto Cloud from the Gitlab previews sample
- Remove references to the catalog, which was deprecated 2 releases ago
=> Update the GitLab sample for preview environments

netlify.toml
redirect for getting started samples. Should fix broken links in getting started repositories.
=> redirect getting started samples to new location

netlify.toml
- Removed an erroneous `:splat` redirect that took precedence over other, correct redirects
- Added missing redirects
=> Fixing missing and erroneous redirects

netlify.toml
Fix redirects for old versions, used by the Okteto UI
=> Fix broken redirects for 1.16 and 1.17

src/content/get-started/deploy-first-env.mdx, src/content/guides/samples/aspnetcore.mdx, src/content/guides/samples/golang.mdx, src/content/guides/samples/java.mdx, src/content/guides/samples/node.mdx, src/content/guides/samples/php.mdx, src/content/guides/samples/python.mdx, src/content/guides/samples/ruby.mdx
Now our samples are executed in SH, users cannot take advantage of smart builds when running our samples.
This PR updates our samples to use pre-built images and speed up the execution of the sample.
This PR must be merged in combination with:
- https://github.com/okteto/movies-with-helm/pull/9
- https://github.com/okteto/movies-with-compose/pull/15
- https://github.com/okteto/aspnetcore-getting-started/pull/12
- https://github.com/okteto/go-getting-started/pull/18
- https://github.com/okteto/java-gradle-getting-started/pull/6
- https://github.com/okteto/java-maven-getting-started/pull/9
- https://github.com/okteto/node-getting-started/pull/10
- https://github.com/okteto/php-getting-started/pull/11
- https://github.com/okteto/python-getting-started/pull/16
- …
=> Don't build images, to make the getting started guides run faster

src/content/get-started/overview.mdx
This section is already on the first section of https://www.okteto.com/docs/, I think it's redundant here. wdyt?
=> Remove redundant overview section

.prettierrc.json, docusaurus.config.js, sidebars.js, src/content/manifest/index.mdx, src/styles/main.scss
This will add page content to sections, removing the need of an "Overview" page.
To do this some styles had to be changed and the sidebar.js file needed to be reorganized. 
In this first example, I did it to the `Okteto Manifest` section, now it doesn't have an "Overview" page. Redirections need to be applied when doing this, as the path changes to `whatever/index` internally, and `whatever` as the canonical URL path.
=> Fix sidebars to allow index pages on sections

src/content/reference/manifest-migration.mdx, versioned_docs/version-1.17/reference/manifest-migration.mdx
The Okteto CLI is linking to this file. We don'0t need it on the sidebar, but we can keep it for now
=> Keep manifest migration but not indexed

sidebars.js, src/content/guides/samples/more.mdx, src/content/guides/tutorials/compose-getting-started.mdx, src/content/guides/tutorials/getting-started-with-okteto.mdx, src/content/guides/tutorials/getting-started-with-pipelines.mdx
Have a dedicated index page for our samples. This makes our nivigation more intuitive and it also makes it possible to refer to all the samples with a single link.
Keeping current names to avoid redirects
=> Index page for samples

src/content/self-hosted/install/argocd.mdx, versioned_docs/version-1.17/self-hosted/install/argocd.mdx
This PR removes the "kind: mutationwebhook" from the argocd guide so it covers all kinds, including validation webhook in the cabundle ignore difference section.
=> docs: include validation webhook in argo cd guide

src/content/preview/using-gitlab-cicd.mdx
Using the `stable` tag in gitlab sample to avoid upgrading the cli version on every release
=> Using okteto/okteto:stable in github sample

src/theme/NavbarItem/DocsVersionDropdownNavbarItem.js
I think it is confusing to see in the dropdown our current working version and not notify users which one is the latest available version. We can mark it as such like this:
=> Mark lastest version in dropdown

src/content/previews/using-gitlab-cicd.mdx, versioned_docs/version-1.18/preview/using-gitlab-cicd.mdx
Use `CI_PROJECT_URL` instead of `CI_REPOSITORY_URL` in the gitlab previews sample.
`CI_REPOSITORY_URL` comes with the user token, which is less secure, and it also break private submodules.
Using `CI_PROJECT_URL` allows Okteto to clone git submodules using the SSH key
=> Update gitlab previews sample

README.md, docusaurus.config.js, netlify.toml
This adds an additional redirect for all URLs so we can link to next _unreleased_ version without having to specify or know the "next version" elsewhere. This is planned to be used for the Okteto UI app, to reference docs from next/unreleased chart version.
For example, at time of writing, "current" (unreleased) version is specified to _1.19_. With this change we can link to https://www.okteto.com/docs/unrelesed/development instead of https://www.okteto.com/docs/1.19/development, the new redirect will bring user to the expected version. This way we keep the definition of next/"current" version here, and in a single place.
Updated readme so we take this into account for future updates to docs versions, since just like the _official_ version we would need to update the new redirect …
=> Redirect /unreleased/* paths to currently unreleased version

src/content/index.md, versioned_docs/version-1.18/index.md
Updating the link to the autoscaler from the welcome page.
I think the new page gives more context about the autoscaler than the technical configuration reference
=> Update link to garbage collector

src/content/core/okteto-manifest.mdx, src/content/reference/okteto-manifest.mdx
This PR comes with the following changes:
- Say deploy on remote is recommended
- Explain deploy on remote right after explaining the deploy commands, and before deploying with compose or divert
- Explain it runs in Buildkit
=> Improve Deploy on Remote docs

src/content/development/using-okteto-cli.mdx
Compose preferred name has changed from `docker-compose.yaml` to `compose.yaml` ([Link to spec](https://github.com/compose-spec/compose-spec/blob/master/spec.md#compose-file)):
> The default path for a Compose file is compose.yaml (preferred) or compose.yml that is placed in the working directory. Compose also supports docker-compose.yaml and docker-compose.yml for backwards compatibility of earlier versions. If both files exist, Compose prefers the canonical compose.yaml.
[CLI PR](https://github.com/okteto/okteto/pull/4209)
=> docs: adds compose.yaml as part of the docker compose files

src/content/core/container-registry.mdx
The current registry section instructs the user to push images to the Okteto Registry directly, but our recommended way to interact with the Okteto Registry is via the Okteto Manifest and the `okteto build` command
=> Rewrite Okteto Registry section

src/content/core/okteto-variables.mdx
Adds the description for the new `OKTETO_LOCAL_REGISTRY_STORE_ENABLED` env var
=> docs: add description for OKTETO_LOCAL_REGISTRY_STORE_ENABLED

src/content/self-hosted/install/auth/google.mdx, versioned_docs/version-1.19/self-hosted/install/auth/google.mdx
Fix typo in Google OAuth guide
=> Replace "clientId" by "clientSecret"

src/content/reference/okteto-manifest.mdx
Although this behavior is confusing, I think we should document it
=> Document when `build` overrides the image of Docker Compose services

src/content/release-notes.mdx, versioned_docs/version-1.19/release-notes.mdx
Kubernetes `1.25`  will not be support on next Okteto version, so I'm adding the deprecation notice
=> Added deprecation notice in 1.19 to indicate the support of Kubernetes 1.25 will be removed on next release

src/content/admin/registry-credentials/index.mdx, src/content/self-hosted/helm-configuration.mdx
Starting on Chart 1.20, the Registry Credentials pull secrets operator is enabled by default, deprecating the functionality that writes these credentials to the nodes.
=> Document pull secrets operator enabled by default

src/content/core/okteto-variables.mdx
Adds documentation about `OKTETO_SUPPORT_STACKS_ENABLED`. 
Defaults to true
If not set it will determine that all the files that could be used as compose/stack are compose files
If set it will detect if it's a compose or stack based on the name
=> docs: stack support enabled feat flag

netlify.toml, src/content/self-hosted/manage/crds.mdx
Fix https://okteto.slack.com/archives/C02SX9665RP/p1715785267007669
Any index.html files should redirect to the subdirectory:
https://deploy-preview-733--okteto-docs.netlify.app/docs/reference/okteto-cli/index.html should redirect to https://deploy-preview-733--okteto-docs.netlify.app/docs/reference/okteto-cli/
https://deploy-preview-733--okteto-docs.netlify.app/docs/reference/manifest/index.html should redirect to https://deploy-preview-733--okteto-docs.netlify.app/docs/reference/okteto-manifest
=> Redirect index.html URLs

src/content/core/credentials/environment-variables.mdx, src/content/core/okteto-variables.mdx
Fix some docs to follow the following rules:
- Links to docs always use *.mdx extension
- Don't link to versioned docs
=> Fix links to use *.mdx references

src/content/release-notes.mdx, versioned_docs/version-1.20/release-notes.mdx
This PR updates the 1.20 release notes to do the following:
- Add a deprecation notice section and a link to the doc about Okteto Stacks deprecation
- Move global tolerations and priority class to the "Features" section
=> Add deprecation notice about Okteto Stacks

src/content/get-started/deploy-your-app/index.mdx, versioned_docs/version-1.18/get-started/deploy-your-app/index.mdx, versioned_docs/version-1.19/get-started/deploy-your-app/index.mdx, versioned_docs/version-1.20/get-started/deploy-your-app/index.mdx
Follow-up on https://github.com/okteto/getting-started/pull/2
This PR updates the Node base image version from 14 to 20 from the summary manifest on the first page of the `get-started` tutorial to match the actual version used by the [`getting-started`](https://github.com/okteto/getting-started) project (upgraded in [this PR](https://github.com/okteto/getting-started/pull/2))
=> Update Node image version in the tutorial

src/content/get-started/deploy-your-app/index.mdx, versioned_docs/version-1.18/get-started/deploy-your-app/index.mdx, versioned_docs/version-1.19/get-started/deploy-your-app/index.mdx, versioned_docs/version-1.20/get-started/deploy-your-app/index.mdx
Related: https://github.com/okteto/docs/pull/744
Currently, we don't have a `dev` section as part of the `get-started` tutorial but the final manifest we are supposed to obtain by following the tutorial does, so I think it's better to remove these references for now to match the actual content of the tutorial. We can always recover this part if we finally decide to include this section.
See: https://www.okteto.com/docs/get-started/deploy-your-app/#what-you-will-be-building
So for now, in case you agree, I'm removing the `dev` section from the final manifest and the summary of the sections.
Also added the `name` field to strictly match that manifest on the first page of the tutorial with the one resulted after following all the steps.
=> Update summary and manifest on the `get-started` first page

src/content/release-notes.mdx, versioned_docs/version-1.19/release-notes.mdx, versioned_docs/version-1.20/release-notes.mdx
This PR updates the release notes for the Okteto chart `1.20.1` and `1.19.4`.
=> `1.20.1` + `1.19.4` release notes

src/content/admin/cleanup.mdx, versioned_docs/version-1.20/admin/cleanup.mdx
updating from `push` to deploy, since `push` is deprecated
=> update sleep docs to use okteto deploy instead of okteto push

src/content/release-notes.mdx, versioned_docs/version-1.21/release-notes.mdx
The okteto autoscaler was deprecated a few releases ago, but we didn't mention it in the release notes
=> Announce okteto autoscaler deprecation

src/content/admin/registry-credentials/amazon-ecr.mdx
It looks like using `h1` tags in the content of a page is discouraged, here is a [conversation](https://github.com/facebook/docusaurus/issues/1828) in the Docusaurus repository about it. Docusaurus doesn't inject an ID for first-level headings so we cannot have links directly to these sections. In the [official docs](https://docusaurus.io/docs/markdown-features/toc#markdown-headings) they only talk about `2`, `3` and `4` levels, not mention about `1` AFAIK, but it looks like it generates some issues, e.g. the main title of the page just disappears if there are other `h1`:
|Before|After|
|---|---|
|<img width="900" alt="image" src="https://github.com/okteto/docs/assets/13395148/3d880975-fb71-4377-8221-d8e0696b8556">|<img width="900" alt="image" …
=> Adjust heading levels on `amazon-ecr` page

src/content/core/okteto-variables.mdx, versioned_docs/version-1.20/core/okteto-variables.mdx, versioned_docs/version-1.21/core/okteto-variables.mdx
I've noticed that the docs has missing `echo` for `$OKTETO_ENV` to work.
=> Add missing `echo` for `$OKTETO_ENV` examples

src/content/previews/using-github-actions.mdx, src/content/previews/using-gitlab-cicd.mdx, versioned_docs/version-1.22/previews/using-github-actions.mdx, versioned_docs/version-1.22/previews/using-gitlab-cicd.mdx
- Update the GitHub Action to deploy preview environments to use GitHub Actions concurrency.
- Also, remove references to `scope` from the getting started guides, since we default to `scope: global` now and using `scope: personal` is an advanced scenario that doesn't need to be introduced in the getting started guide
Related PRs:
- https://github.com/okteto/deploy-preview/pull/58
- https://github.com/okteto/build/pull/23
=> Update previews to use github action concurrency

src/content/core/okteto-variables.mdx, versioned_docs/version-1.20/core/okteto-variables.mdx, versioned_docs/version-1.21/core/okteto-variables.mdx, versioned_docs/version-1.22/core/okteto-variables.mdx
In the example we refer to `$resourceName` instead of `$bucketName`
=> Fix typo in `$OKTETO_ENV` example

src/content/core/endpoints/automatic-ssl.mdx
make it more evident that annotation examples we are showing in [are talking about Kubernetes services ](https://www.okteto.com/docs/core/endpoints/automatic-ssl/#auto-create-ingresses-from-services) are about Kubernetes services and not Okteto manifests
=> make it more evident that we are talking about Kubernetes services 

src/content/core/container-registry.mdx, versioned_docs/version-1.12/cloud/registry.mdx, versioned_docs/version-1.13/cloud/registry.mdx, versioned_docs/version-1.14/cloud/registry.mdx, versioned_docs/version-1.15/cloud/registry.mdx, versioned_docs/version-1.16/core/components/container-registry.mdx, versioned_docs/version-1.17/core/components/container-registry.mdx, versioned_docs/version-1.18/core/components/container-registry.mdx, versioned_docs/version-1.19/core/container-registry.mdx, versioned_docs/version-1.20/core/container-registry.mdx, versioned_docs/version-1.21/core/container-registry.mdx, versioned_docs/version-1.22/core/container-registry.mdx, versioned_docs/version-1.23/core/container-registry.mdx
I think this is an old typo we never noticed because `OKTETO_REGISTRY` does not exist, nor appears to have existed in the past.
I've checked [Okteto CLI 2.0.0](https://github.com/okteto/okteto/blob/release-2.0/pkg/model/const.go#L202) and it was still called `OKTETO_REGISTRY_URL` like today: https://github.com/okteto/okteto/blob/master/pkg/model/const.go#L150
To validate run `okteto deploy` with this manifest
```
deploy:
- env | grep OKTETO_REG
```
=> fix OKTETO_REGISTRY_URL var

src/content/self-hosted/manage/backup-restore.mdx, versioned_docs/version-1.17/self-hosted/manage/backup-restore.mdx, versioned_docs/version-1.18/self-hosted/manage/backup-restore.mdx, versioned_docs/version-1.19/self-hosted/manage/backup-restore.mdx, versioned_docs/version-1.20/self-hosted/manage/backup-restore.mdx, versioned_docs/version-1.21/self-hosted/manage/backup-restore.mdx, versioned_docs/version-1.22/self-hosted/manage/backup-restore.mdx, versioned_docs/version-1.23/self-hosted/manage/backup-restore.mdx
Fixing a reference to secrets in our backup/restore.
We probably introduced this error when renaming "Secrets" to "Variables" in the product
=> Refer to Kubernetes secrets when documenting the backup/restore process

src/content/core/okteto-variables.mdx
With this PR we aim to document the behaviour that the Okteto CLI implements, about propagating the variables of `deploy` to the `destroy`.
I am using the term `command item` to refer to the specific line/command/array item, but it overlaps with the "CLI command" such as deploy/destroy, so if someone has better copy, that is less confusing, please share it :)
=> docs scenario sharing vars deploy to destroy

src/styles/main.scss
The base paragraph text is actually 18px, but for whatever reason the code block was at some point changed 16px. This causes the text to look misaligned and wonky when there's a mix of regular and inline `code` texts present on same lines.
It appears the vertical align was set to _middle_ to [fix alignment in the default Docusaurus styles](https://github.com/facebookincubator/infima/pull/113) (aka [Infirma](https://docusaurus.io/docs/next/styling-layout#styling-your-site-with-infima)), but that clashes with our custom body and code fonts.
Fixed by setting 18px as default size also for inline code blocks, and resetting the `vertical-align` to _baseline_ instead.
While at it, also removing unnecessary props like `border-radius` and `border` that are already set through the underlying …
=> Fix inline code blocks to look vertically balanced

src/content/self-hosted/helm-configuration.mdx
Documenting the cronjob as part of the `insights` component
=> Document the Insights cronjob that pre-computes metrics

sidebars.js, src/content/get-started/deploy-your-app/index.mdx, src/content/get-started/dev-quickstart.mdx, src/content/get-started/install-okteto-cli.mdx, src/content/get-started/install/amazon-eks.mdx, src/content/get-started/install/civo.mdx, src/content/get-started/install/digitalocean-doks.mdx, src/content/get-started/install/google-gke.mdx, src/content/get-started/install/index.mdx, src/content/get-started/install/microsoft-aks.mdx, src/content/get-started/install/openshift.mdx
I have been experimenting with the location of the Okteto CLI installation instructions. In the current layout, it's inside the "Getting Started for Platform Engineers" section, which looks weird.
This PR moves the Okteto installation guide to the top of the "Get Started" section. This can also be useful if we start implementing Okteto CLI commands to help with the Okteto Chart installation.
Other changes:
- Remove the Okteto CLI configuration step from the CLI installation guide
- Explain how to configure the CLI as part of the Chart installation guide
- Use the Okteto CLI installation guide as a single point of true and link to it from the Developer's Quickstart
=> Refactor The Okteto CLI installation instructions

src/content/admin/cloud-credentials/gcp.mdx
https://deploy-preview-872--okteto-docs.netlify.app/docs/1.25/admin/cloud-credentials/gcp-cloud-credentials/ is the impacted page
=> Update gcp doc with instructions on how to get project number and to use same terms than in the UI

src/content/development/deploy/deploy-from-git.mdx, src/content/development/deploy/develop-on-okteto-button.mdx, versioned_docs/version-1.14/cloud/deploy-from-git.mdx, versioned_docs/version-1.14/cloud/develop-on-okteto-button.mdx, versioned_docs/version-1.14/samples/ruby.mdx, versioned_docs/version-1.15/cloud/deploy-from-git.mdx, versioned_docs/version-1.15/cloud/develop-on-okteto-button.mdx, versioned_docs/version-1.15/samples/ruby.mdx, versioned_docs/version-1.16/deploy/deploy-from-git.mdx, versioned_docs/version-1.16/deploy/develop-on-okteto-button.mdx, versioned_docs/version-1.17/deploy/deploy-from-git.mdx, versioned_docs/version-1.17/deploy/develop-on-okteto-button.mdx, versioned_docs/version-1.18/deploy/deploy-from-git.mdx, versioned_docs/version-1.18/deploy/develop-on-okteto-button.mdx, versioned_docs/version-1.19/development/deploy/deploy-from-git.mdx, versioned_docs/version-1.19/development/deploy/develop-on-okteto-button.mdx, versioned_docs/version-1.20/development/deploy/deploy-from-git.mdx, versioned_docs/version-1.20/development/deploy/develop-on-okteto-button.mdx, versioned_docs/version-1.21/development/deploy/deploy-from-git.mdx, versioned_docs/version-1.21/development/deploy/develop-on-okteto-button.mdx, versioned_docs/version-1.22/development/deploy/deploy-from-git.mdx, versioned_docs/version-1.22/development/deploy/develop-on-okteto-button.mdx, versioned_docs/version-1.23/development/deploy/deploy-from-git.mdx, versioned_docs/version-1.23/development/deploy/develop-on-okteto-button.mdx, versioned_docs/version-1.24/development/deploy/deploy-from-git.mdx, versioned_docs/version-1.24/development/deploy/develop-on-okteto-button.mdx, versioned_docs/version-1.25/development/deploy/deploy-from-git.mdx, versioned_docs/version-1.25/development/deploy/develop-on-okteto-button.mdx
The hash-based routing was replaced over ~1½y ago (_v1.**8**_), but we apparently missed to update these examples. So it's safe to change these to use the expected pathname structure used since. 
Note that we still have a fallback redirects in place on the actual app, so any existing URLs that continue to use deploy button with this `/#/` prefix will continue to work nevertheless. But it would be preferable if we could figure out if any customers actually use this and get them updated.
=> Remove hash part in URLs of deploy button examples

src/content/admin/cloud-credentials/gcp.mdx, versioned_docs/version-1.25/admin/cloud-credentials/gcp.mdx
Fixes wrong heading ident in gcp cloud credentials doc.
=> docs: wrong ident

src/content/self-hosted/helm-configuration.mdx
Adding documentation for the release name max length.
I've added `nameOverride` and `fullnameOverride` under the "Advanced Configuration" to reduce noise, as these are mostly used in edge-case scenarios where the release name is very long.
I've added the recently introduced validation rules for the release name max length.
=> update helm config adding release name rules and settings

src/content/core/remote-execution.mdx, src/content/reference/okteto-manifest.mdx
Document the `context` field for remote execution and review some sections in the "Remote Execution" doc to align better with the new SSH agent behavior.
=> Document "context" property for Deploy on Remote

src/content/self-hosted/manage/crds.mdx, versioned_docs/version-1.22/self-hosted/manage/crds.mdx, versioned_docs/version-1.23/self-hosted/manage/crds.mdx, versioned_docs/version-1.24/self-hosted/manage/crds.mdx, versioned_docs/version-1.25/self-hosted/manage/crds.mdx, versioned_docs/version-1.26/self-hosted/manage/crds.mdx
Added documentation to explain how to configure private registry credentials with IAM roles using CRDs. The current section was a bit mixed between static credentials and AWS ones, so I opted by creating sub sections with each type of credentials to make it clearer.
I added the changes up to `1.22` version which is the one where we included AWS IAM role configurations: https://www.okteto.com/docs/release-notes/#1220
=> Added documentation about how to configure IAM roles credentials for private registries using CRDs approach

src/content/reference/okteto-manifest.mdx, versioned_docs/version-1.26/reference/okteto-manifest.mdx
We were missing `runAsNonRoot` and `allowPrivilegeEscalation` from the list of supported fields for the `securityContext` section of the Okteto Manifest. I just updated ongoing and current versions
=> Updated supported fields for the securityContext section of the Okteto Manifest

src/content/release-notes.mdx, src/content/self-hosted/helm-configuration.mdx, versioned_docs/version-1.26/release-notes.mdx
We introduced a change that makes it easier to migrate the default-backend, and requires no manual changes.
I've tested migration from `1.26` to "latest" and backwards, and the manual steps were not required as expected, so I am proposing to remove these steps that add additional friction in an upgrade and are no longer needed.
I would keep them in the `1.26` docs, as the change will be available from `1.27` onwards, so migrating from `1.27` to `1.28` will no require manual steps.
=> Remove manual migration steps for default-backend

src/content/self-hosted/helm-configuration.mdx
Document the new globals field to define the ttlSecondsAfterFinished for jobs created by the Okteto Control Plane
=> Document "jobs.ttlSecondsAfterFinished"

src/content/admin/custom-installer-image.mdx, src/content/core/remote-execution.mdx, src/content/self-hosted/helm-configuration.mdx
This PR documents the workdir of remote execution and updates the "custom installer image" docs to accommodate to the new chart image format.
=> Some fixes for 1.27 release

sidebars.js, src/content/self-hosted/manage/airgap.mdx, src/content/variables.json
This is still work in progress, but I want to share it to visualize the expected results once all the work is done
=> AirGap Networks installation guide

src/content/release-notes.mdx, versioned_docs/version-1.24/release-notes.mdx, versioned_docs/version-1.25/release-notes.mdx, versioned_docs/version-1.26/release-notes.mdx
I detected that `1.23.3` version was missing in the release notes for `1.24` and higher versions. We added it only for the `1.23` versioned docs. Added such version in all missing versioned docs
=> Added missing version 1.23.3 for release notes

src/content/reference/okteto-manifest.mdx
This PR is adding documentation for a missing manifest reference for `deploy.compose` which can also be declared using the object notation.
| Before                                                                                                                                           | After                                                                                                                                            |
|--------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="1068" alt="Screenshot 2024-12-10 at 09 54 11" …
=> Document `deploy.compose` object notation

src/content/self-hosted/manage/air-gapped.mdx, versioned_docs/version-1.27/self-hosted/manage/air-gapped.mdx
Using the key as documented on https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx/4.11.2#:~:text=controller.image.registry,registry.k8s.io%22
Change is on https://deploy-preview-949--okteto-docs.netlify.app/docs/self-hosted/manage/air-gapped/#step-3-update-helm-configuration
=> fix key for ingress-nginx and okteto-nginx in the airgap docs

src/content/core/remote-execution.mdx, src/content/release-notes.mdx, versioned_docs/version-1.27/core/remote-execution.mdx, versioned_docs/version-1.27/release-notes.mdx
This PR includes:
* A bullet point in the release notes indicating that some binaries were removed from the Okteto's default runner image
* Restore `kustomize` (and `curl` this was never deleted from the imaged, but it was from the docs) as binary included in the default runner image
* Add entry for `1.27.1` version of chart where we will restore the `kustomize` binary
=> Indicate removed binaries in the release notes, and restore `kustomize` binary as part of the default runner image

src/content/reference/okteto-cli.mdx
This needs to wait until we release the Okteto CLI 3.2.0
=> Document `okteto validate`

src/content/release-notes.mdx, src/content/variables.json
Changes to reflect that `1.30` version of Okteto will not support Kubernetes version `1.28`. 
@codyjlandstrom Do we want to mention something about now supporting one less version of Kubernetes per release, or it is fine just the regular removal notice?
=> DEV-863: Remove support of Kubernetes version 1.28

src/content/self-hosted/install/github.mdx, versioned_docs/version-1.30/self-hosted/install/github.mdx
Add double quotes in appId. It could be converted into a exponential and fail. Double quoting makes helm treat it like a string
=> Fix formatting of appId in GitHub installation instructions

src/content/reference/okteto-manifest.mdx, versioned_docs/version-1.31/reference/okteto-manifest.mdx
As we already had issues in the past thinking that the HTTP header we are including as part of divert is `baggage.okteto-divert` instead of the key `okteto-divert` **within** the `baggage` header (Istio driver was injecting the right header, while nginx one was injecting the wrong one), I modified the divert section to indicate that we inject a new key in the `baggage` header, instead of injecting a `baggage.okteto-divert` independent header.
I think this makes it clearer until we have a dedicated documentation for divert, but no problem on declining the changes if we don't consider this an improvement
=> Clarification in divert section of the manifest to indicate that okteto-divert is a key within the baggage header

src/content/admin/integrations/okta-user-deprovisioning.mdx, versioned_docs/version-1.30/admin/integrations/okta-user-deprovisioning.mdx, versioned_docs/version-1.31/admin/integrations/okta-user-deprovisioning.mdx, versioned_docs/version-1.32/admin/integrations/okta-user-deprovisioning.mdx
For the Okta Deprovision config we were referring to Helm setting, but Okta deprovisioning is not configured through helm values. 
Clarified that, and indicate that the value used in the `Okta Event Hook Token` is the Authorization secret defined in the Okta side
=> Clarified where Okta deprovision config is provided in Okteto

versioned_docs/version-1.32/admin/integrations/okta-user-deprovisioning.mdx
In this PR I added some clarification about Okta clarification https://github.com/okteto/docs/pull/1030, but in the `1.32` version I forgot to add one change I did in the other versions, so, sending this to have the same in the different versions
=> Added missed clarification on Okta deprovisioning config for 1.32 version

src/content/reference/okteto-cli.mdx
CLI `3.8.0` includes a new option for the `okteto namespace list` command to indicate the command output. This PR addes the flag to the command documentation
=> Added 'output' flag for the namespace list command

src/content/self-hosted/helm-configuration.mdx
- Updated the globals.nodeSelectors section to note that the dev node selectors are only applied if tolerations.devPool is defined
- Added an explicit :::note explaining the legacy behavior and potential future change
- Updated the globals.tolerations section to reflect that defining tolerations.dev is required for nodeSelectors.dev to be respected
- Added cross-references between tolerations and nodeSelectors for improved discoverability
=> Clarify NodeSelector and Toleration Behavior for Dev Workloads

src/content/get-started/deploy-your-app/endpoints.mdx
This PR adds a concise section about using endpoints with Docker Compose to the getting started guide for deploying applications.
- Added a new "Using Endpoints with Docker Compose" section to 
- Includes a practical example showing how to configure endpoints in a docker-compose.yml file
- Explains the basic concept and links to comprehensive documentation
- Positioned after the Kubernetes Ingress section for logical flow
The current endpoints documentation only covers Kubernetes Ingress resources, but many users start with Docker Compose. This addition provides a quick introduction to Docker Compose endpoints while keeping the getting started guide concise.
- Verified MDX syntax is correct
- Ensured all code blocks are properly formatted
- Confirmed the link to the Docker Compose …
=> Add Docker Compose endpoints section to getting started guide

src/content/reference/okteto-manifest.mdx
Add documentation for the support of the field ReadOnlyRootFilesystem in the Okteto manifest as part of the `dev` section. This will be available in `3.11` version of the CLI
=> Add documentation for the support of the field ReadOnlyRootFilesystem in the Okteto manifest

src/content/self-hosted/install/github.mdx, versioned_docs/version-1.35/self-hosted/install/github.mdx
GitHub App creation dialog doesn't have an `Authorization callback URL` field (it might had it in the past, but now it is not present). So, I'm changing it to add the callback URL, and set the one it should be in the `Authorization callback URL`
=> Changed instructions about the URls to configure when creating a github app
