CONTRIBUTING.md
=> added note about versions in contributing guide

src/content/enterprise/administration/configuration.mdx, src/content/enterprise/administration/volume-snapshots.mdx
Signed-off-by: Teresa Romero <teresa@okteto.com>
Added support for the new flags regarding VolumeSnapshots usage when creating PVC
=> Added docs for config flags for volumeSnapshots

src/content/reference/cli.mdx, src/content/reference/manifest.mdx, versioned_docs/version-0.11/reference/cli.mdx, versioned_docs/version-0.11/reference/manifest.mdx, versioned_docs/version-0.12/reference/cli.mdx, versioned_docs/version-0.12/reference/manifest.mdx
=> rephrase what okteto managed clusters mean

src/content/reference/manifest.mdx, versioned_docs/version-0.11/reference/manifest.mdx, versioned_docs/version-0.12/reference/manifest.mdx
@pchico83 can you confirm that this is the correct format? checkr reported this.
=> update sample to fix typo

sidebars.js, src/content/enterprise/administration/custom-installer-image.mdx, src/content/tutorials/aws-lambda.mdx
Simon has been asking for docs on this. I think this is a useful scenario to document as we invest more in dev environments that expand more than just containers. I want it in /docs instead of on community, because I want Simon to understand that this is a fully supported scenario.  @pchico83 what do you think? 
I also want to make https://github.com/okteto/aws-lambda public along with it (it's a minimal sample)
=> How to Deploy an AWS Lambda

src/content/reference/docker-compose.mdx
Adds documentation for health check on compose
=> docs: add healthcheck documentation

src/content/api.mdx, src/content/enterprise/civo.mdx, versioned_docs/version-0.10/api.mdx, versioned_docs/version-0.11/api.mdx, versioned_docs/version-0.11/enterprise/civo.mdx, versioned_docs/version-0.12/api.mdx, versioned_docs/version-0.12/enterprise/civo.mdx, versioned_docs/version-0.13/api.mdx, versioned_docs/version-0.13/enterprise/civo.mdx
As part of the SEO improvements tasks, some images were missing alt attributes.
https://app.hubspot.com/content-strategy/5418301/recommendations/domain/1309617/hostname/1949392/category/ON_PAGE_SEO/type/ADD_IMAGE_ALT_TEXT
=> SEO improvements - Fix missing alt attributes

versioned_docs/version-0.10/enterprise/administration/cleanup.mdx, versioned_docs/version-0.10/enterprise/administration/private-repositories/ssh-key.mdx, versioned_docs/version-0.11/enterprise/administration/cleanup.mdx, versioned_docs/version-0.11/enterprise/administration/private-repositories/ssh-key.mdx, versioned_docs/version-0.12/enterprise/administration/cleanup.mdx, versioned_docs/version-0.12/enterprise/administration/private-repositories/ssh-key.mdx
Make sure all images link are correct
https://app.hubspot.com/content-strategy/5418301/recommendations/domain/1309617/hostname/1949392/category/USER_EXPERIENCE/type/FIX_BROKEN_RESOURCES
=> SEO improvements - fix broken images link

src/content/enterprise/install/overview.mdx, versioned_docs/version-0.10/enterprise/install/overview.mdx, versioned_docs/version-0.11/enterprise/install/overview.mdx, versioned_docs/version-0.12/enterprise/install/overview.mdx, versioned_docs/version-0.13/enterprise/install/overview.mdx
As part of the SEO improvements tasks, this PR removes multiple `<h1>` on some pages
https://app.hubspot.com/content-strategy/5418301/recommendations/domain/1309617/hostname/1949392/category/ON_PAGE_SEO/type/ADD_H1_TAGS?page=1
=> SEO improvements - Remove multiple <h1>

src/content/enterprise/install/releases.mdx
@jpf-okteto I didn't add all your work on Cert Manager as I know if it's not enable by default or whether we should document it in this release. Let me know if we need to add it to the release notes and the configuration docs if needed
=> Release notes for 0.15.0

src/content/reference/manifest.mdx
=> docs: add ephemeral storage requests and limits

src/content/reference/manifest.mdx
Context: https://okteto.slack.com/archives/C02SX9665RP/p1662123100938989
=> removed codeblock from sidebar

src/content/enterprise/administration/certificates.mdx, src/content/enterprise/administration/configuration.mdx, src/content/enterprise/aks.mdx, src/content/enterprise/aks/config.yaml, src/content/enterprise/civo.mdx, src/content/enterprise/digitalocean.mdx, src/content/enterprise/eks.mdx, src/content/enterprise/gke.mdx, src/content/enterprise/install/deployment.mdx, src/content/enterprise/install/preparation.mdx
Milestone 3 of Cert Manager removal
=> Fully deprecate Cert Manager

src/content/enterprise/administration/certificates.mdx, src/content/enterprise/administration/configuration.mdx, src/content/enterprise/administration/github.mdx, src/content/enterprise/aks.mdx, src/content/enterprise/aks/config.yaml, src/content/enterprise/civo.mdx, src/content/enterprise/digitalocean.mdx, src/content/enterprise/eks.mdx, src/content/enterprise/gke.mdx, src/content/enterprise/install/deployment.mdx, src/content/enterprise/install/overview.mdx, src/content/enterprise/install/preparation.mdx, src/content/enterprise/install/troubleshooting.mdx
This PRs makes it clearer that installing Cert MAnager is optional.
=> Document installation without Cert Manager

src/content/enterprise/administration/configuration.mdx
documentation on timeout handling by the server when communicating with the client
https://github.com/okteto/buildkit/pull/18
=> add keepalive server docs

src/content/enterprise/administration/configuration.mdx, src/content/enterprise/install/releases.mdx
Document how to enabled/disabled user pod affinities, to prefer pods in the same namespace to be deployed in the same node
=> Document userPodAffinity setting

src/content/self-hosted/install/releases.mdx
=> Fix typo in 1.0 release notes

src/content/self-hosted/administration/configuration.mdx, src/content/self-hosted/install/releases.mdx
Missing PR are:
- https://github.com/okteto/docs/pull/197
- https://github.com/okteto/docs/pull/203
- https://github.com/okteto/docs/pull/196
=> Adding missing commits that got lost when switching to 1.0 docs

src/content/cloud/custom-domains.mdx
All our SaaS/Self-hosted users can benefit from custom domains if cert-manager is available on their clusters.
=> Document how to use custom domain in SaaS and Self-Hosted

src/content/self-hosted/administration/configuration.mdx
Signed-off-by: Agustin Ramiro Diaz <agustin.ramiro.diaz@gmail.com>
=> Document extraRoleBindings

src/content/reference/manifest.mdx
Added documentation related to the global forward. Merge docs when added feat to a new CLI release.
=> feat: add global forward doc

src/content/reference/manifest.mdx
=> add serviceAccount to manifest reference

src/content/self-hosted/install/releases.mdx
=> add release notes for 1.1.0

src/content/reference/manifest.mdx
Adds documentation about https://github.com/okteto/okteto/pull/3064
=> docs: adds depends_on

src/content/reference/cli.mdx
Documents: https://github.com/okteto/okteto/pull/3019
=> docs: add no bash flag documentation

versioned_docs/version-0.13/reference/manifest.mdx, versioned_docs/version-0.14/reference/manifest.mdx
Making the change from #182 in older versions as well.
=> removed codeblock from sidebar in older versions as well

src/content/self-hosted/administration/github.mdx, src/content/self-hosted/install/deployment.mdx, versioned_docs/version-1.1/self-hosted/install/deployment.mdx
=> document that github secrets can be added in the secret as well

src/content/self-hosted/administration/configuration.mdx
Regarding this issue, already solved
https://github.com/okteto/app/issues/4994
=> Added doc to PSP

src/content/self-hosted/administration/configuration.mdx
Request: https://github.com/okteto/docs/pull/255#issuecomment-1323794083
=> Fixed: Duplicated PodSecurityPolicy Documentation

src/content/self-hosted/install/releases.mdx
Info gathered from https://github.com/okteto/app/releases/tag/chart%2F1.2.0-rc.1
=> Add-release-notes

versioned_docs/version-1.2/self-hosted/administration/configuration.mdx, versioned_docs/version-1.2/self-hosted/install/releases.mdx
Signed-off-by: Agustin Ramiro Diaz <agustin.ramiro.diaz@gmail.com>
=> Fix latest versioned docs to match today's content

src/content/reference/cli.mdx
Document `okteto logs`, implement on this PR:
https://github.com/okteto/okteto/pull/2120
=> Add docs for "okteto logs"

src/content/self-hosted/administration/configuration.mdx, src/content/self-hosted/administration/github.mdx, src/content/self-hosted/aks.mdx, src/content/self-hosted/civo.mdx, src/content/self-hosted/eks.mdx, src/content/self-hosted/install/preparation.mdx
I've also fixed some details on the github.mdx file
=> Guide user to use same github app for auth and integration

src/content/cloud/github-actions.mdx
https://github.com/okteto/docs/issues/268
=> remove deprecated gh actions from documentation

src/content/self-hosted/administration/certificates.mdx, versioned_docs/version-0.11/enterprise/administration/certificates.mdx, versioned_docs/version-0.12/enterprise/administration/certificates.mdx, versioned_docs/version-0.13/enterprise/administration/certificates.mdx, versioned_docs/version-0.14/enterprise/administration/certificates.mdx, versioned_docs/version-0.15/enterprise/administration/certificates.mdx, versioned_docs/version-1.0/self-hosted/administration/certificates.mdx, versioned_docs/version-1.1/self-hosted/administration/certificates.mdx, versioned_docs/version-1.2/self-hosted/administration/certificates.mdx, versioned_docs/version-1.3/self-hosted/administration/certificates.mdx
Signed-off-by: Agustin Ramiro Diaz <agustin.ramiro.diaz@gmail.com>
This has given me some headache while installing :disappointed:
=> Add certificate format to docs

src/content/administration/dashboard.mdx, src/content/reference/manifest.mdx
Documents this change https://github.com/okteto/okteto/issues/2566
=> Added secrets option to okteto manifest build section

src/content/self-hosted/install/releases.mdx, src/content/self-hosted/install/upgrade.mdx
Realted to https://github.com/okteto/installer/issues/293
Signed-off-by: mnevado <nevado.mario@gmail.com>
=> update cert manager doc

src/content/reference/manifest.mdx
Adds documentation for external resources
=> feat: add external documentation

src/content/self-hosted/administration/configuration.mdx
Signed-off-by: mnevado <nevado.mario@gmail.com>
=> Networkpolicies Rules Doc

src/content/self-hosted/administration/configuration.mdx
related to: https://github.com/okteto/app/issues/5463
=> added user pod anti-affinity

src/content/self-hosted/install/releases.mdx, versioned_docs/version-1.4/self-hosted/install/releases.mdx
Signed-off-by: Ignacio Fuertes <nacho@okteto.com>
We have a fix ready to be release. This PR updates the docs to include the release notes
=> Added release notes for the upcoming 1.4.2 which includes a fix for instances with private CAs and self-signed certificates

src/content/cloud/preview-environments/github.mdx, src/content/cloud/preview-environments/gitlab.mdx
Step 1 of forking the repo adds nothing to the guide. Forking the repository is not needed to follow along. Also added clarification for the tokens used in the GH action.
=> updating preview env docs for better readability

src/content/reference/docker-compose.mdx
Related to: https://github.com/okteto/okteto/pull/3385
Fixes #319
=> Added docker-compose v3 resources config

src/content/reference/manifest.mdx
We need to create a doc explaining the divert feature, requirements and use cases.
This PR only adds the technical docs to document the fields in the okteto manifest.
=> Document the Istio divert driver

README.md
=> Added instructions to use Okteto CLI to build the website locally

src/content/reference/cli.mdx, src/content/reference/manifest.mdx
Add documentation for CLI remote deploy feature
=> docs: add remote documentation

.github/CODEOWNERS
Notify Matt of changes in the release notes so we can have early product feedback in the cycle
=> Notify Matt for changes in the release notes

src/content/reference/cli.mdx
Documentation for the command added in this pr https://github.com/okteto/okteto/pull/3404
=> Document kubetoken command

src/content/self-hosted/administration/configuration.mdx, src/content/self-hosted/install/releases.mdx
Document the token-based authentication and add it to the release notes
=> Document token-based authentication method

src/content/getting-started.mdx, src/content/index.md, src/content/using-dev-envs.mdx
First pass at updating content for:
Welcome >> Overview
Welcome >> Getting Started >> Install and Configure
Welcome >> Getting Started >> Development Environments
My focus was general proofreading and consistency. A few items to note:
I just merged a PR that used Okteto UI consistently, but in the Getting Started guide it reads a bit odd to say: "When it's done building the images, it will start deploying your application to the Okteto platform". It also sounds odd to say "... to the Okteto UI". We need some good language for this or to agree that using "Okteto platform" is ok in these situations
I'm not making fundamental changes to structure, format, or content yet
I think there's an opportunity to restructure our docs from the left nav to the layout of the pages themselves
My main …
=> Reviewed and updated content for welcome and getting started docs

src/content/self-hosted/install/releases.mdx, src/content/self-hosted/install/upgrade.mdx
Added release notes for the coming `1.7` chart release
=> Added release notes for 1.7 release

src/content/self-hosted/administration/configuration.mdx, src/content/self-hosted/install/releases.mdx
Release note for https://github.com/okteto/app/issues/6195
=> Document release note for change on buildkit sessionAffinity default value

src/content/self-hosted/administration/configuration.mdx
This makes it easier to navigate between the different auth methods
=> Add links to every auth method

src/content/cloud/deploy-from-git.mdx, src/content/cloud/launch-from-catalog.mdx, src/content/cloud/okteto-cli.mdx, src/content/cloud/okteto-pipeline.mdx, src/content/reference/cli.mdx, src/content/reference/development-containers.mdx, src/content/reference/development-environments.mdx, src/content/reference/file-synchronization.mdx, src/content/reference/manifest-migration.mdx, src/content/reference/manifest.mdx, src/content/tutorials/getting-started-with-okteto.mdx
@rberrelleza @pchico83 I converted most `.yml` extensions to `.yaml` per [this slack thread](https://okteto.slack.com/archives/C043X0H48BZ/p1683013591181909).
I haven't yet looked to see if changing any of these will affect examples or something secondary like that.
=> Update yml to yaml in many cases

src/content/cloud/namespaces.mdx, src/content/reference/cli.mdx
Fixes: https://github.com/okteto/docs/issues/364
=> Documented information about sleep and wake namespace

src/content/reference/manifest.mdx, src/content/self-hosted/install/releases.mdx
List of changes to be published with the release notes for 1.8
=> Release notes for 1.8

src/content/self-hosted/install/releases.mdx, versioned_docs/version-1.8/self-hosted/install/releases.mdx
This release includes a couple of fixes. One in the backend and another one in the CLI
=> Added release notes for 1.8.1 version

src/content/self-hosted/administration/certificates.mdx, versioned_docs/version-1.8/self-hosted/administration/certificates.mdx
A small update of the text to the wildcard cert to make it clear how to use cert-manager to create the wildcard cert.
=> update text on wildcard guide

src/content/cloud/external-resources.mdx
- Added new icons
- Added a "destroy from UI" section
=> Updating external resources doc

src/content/self-hosted/aks.mdx, src/content/self-hosted/digitalocean.mdx, src/content/self-hosted/eks.mdx, src/content/self-hosted/gke.mdx, src/content/self-hosted/install/preparation.mdx, src/content/self-hosted/install/releases.mdx, versioned_docs/version-1.8/self-hosted/install/releases.mdx
This PR adds the release notes for 1.9
=> Release notes 1.9

src/content/self-hosted/administration/configuration.mdx
Document how to expose buildkit behind Kong using the right annotations
=> Document how to expose buildkit behind Kong

src/content/cloud/okteto-cli.mdx, src/content/cloud/okteto-pipeline.mdx, src/content/reference/manifest.mdx
Document in a single place all the environment variables that are available in `okteto deploy`
=> Document the environment variables available in "okteto deploy"

src/content/reference/cli.mdx
=> docs(preview): add labels flag

src/content/self-hosted/administration/configuration.mdx, versioned_docs/version-1.7/self-hosted/administration/configuration.mdx, versioned_docs/version-1.8/self-hosted/administration/configuration.mdx, versioned_docs/version-1.9/self-hosted/administration/configuration.mdx
`provider` key was missing under `storage`. The rest of external providers are ok
=> Fix configuration snippet  for the registry external storage in GCP provider

src/content/reference/cli.mdx
Remaining changes for releaes 2.17.0
=> Update CLI reference for 2.17.0

src/content/administration/dashboard.mdx
Simple updates to provide clarity to the Admin > Users docs based on feedback from customers and the sales team
=> Add clarifications to the Admin > Users feature

src/content/self-hosted/administration/configuration.mdx
Cleaned up https://www.okteto.com/docs/self-hosted/administration/configuration/#nginx-ingress-controller to be more clear 🤞
=> Update ingress controller docs

src/content/reference/cli.mdx
Docs for https://github.com/okteto/okteto/pull/3776
=> New supported flag on okteto preview destroy

src/content/reference/cli.mdx
Docs for https://github.com/okteto/okteto/pull/3570
Part of 2.18 CLI Release, will be merge when this is released
=> New supported commands sleep and wake previews

src/content/self-hosted/administration/certificates.mdx, src/content/self-hosted/administration/configuration.mdx, src/content/self-hosted/install/overview.mdx
=> adding self hosted install videos to the docs

src/content/reference/manifest.mdx, versioned_docs/version-1.6/reference/manifest.mdx
**Related PR: https://github.com/okteto/okteto/pull/3853**
**Images:**
---
=> feat: mention about `--remote` field for `deploy` & `destroy` section in okteto manifest

.github/CODEOWNERS
I'm not an active reviewer for all PRs any longer so removing myself in an attempt to manage my Github notifications a bit better :)
=> Update CODEOWNERS to remove myself

src/content/self-hosted/administration/configuration.mdx
Implemented in https://github.com/okteto/app/commit/864297313e86c71f47613bfd5d2b1a7364d57332
=> Document Priority Class configurations

src/content/self-hosted/administration/configuration.mdx
=> Revert "Document Priority Class configurations"

src/content/administration/okteto-license.mdx
Added some clarification about how to include the Okteto license
=> Added clarification for adding Okteto license

src/content/self-hosted/install/troubleshooting.mdx, src/content/self-hosted/install/upgrade.mdx
Document the usage of a test cluster as a best practice for okteto upgrades
=> Document upgrade best practices

src/content/self-hosted/administration/configuration.mdx, src/content/self-hosted/administration/github.mdx, src/content/self-hosted/aks.mdx, src/content/self-hosted/civo.mdx, src/content/self-hosted/digitalocean.mdx, src/content/self-hosted/eks.mdx, src/content/self-hosted/gke.mdx, src/content/self-hosted/guides/azure-active-directory/index.mdx, src/content/self-hosted/guides/gitlab/index.mdx, src/content/self-hosted/guides/okta/index.mdx, src/content/self-hosted/install/deployment.mdx, src/content/self-hosted/offline.mdx
@rberrelleza I found a few broken links when making a pass to the installation guides.
I thought we were checking for broken links on CI, maybe we aren't checking for references to sections in a doc?
=> Fix broken links

src/content/reference/development-environments.mdx, versioned_docs/version-1.13/reference/development-environments.mdx
Found this broken hyperlink in https://www.okteto.com/docs/reference/development-environments/
=> Fix broken link in overview

sidebars.js, src/content/self-hosted/install/backup-restore.mdx
The platform team has prepared a guide about backing up and restoring an Okteto instance.
This is useful for customers running SH.
=> Document how to backup and restore an Okteto instance

src/content/self-hosted/install/releases.mdx
Release notes draft for 1.14 and configuration updates
=> Okteto 1.14 release notes

src/content/reference/manifest.mdx, versioned_docs/version-1.10/reference/manifest.mdx, versioned_docs/version-1.11/reference/manifest.mdx, versioned_docs/version-1.12/reference/manifest.mdx, versioned_docs/version-1.13/reference/manifest.mdx, versioned_docs/version-1.14/reference/manifest.mdx, versioned_docs/version-1.4/reference/manifest.mdx, versioned_docs/version-1.5/reference/manifest.mdx, versioned_docs/version-1.6/reference/manifest.mdx, versioned_docs/version-1.7/reference/manifest.mdx, versioned_docs/version-1.8/reference/manifest.mdx, versioned_docs/version-1.9/reference/manifest.mdx
=> Add missing word

src/content/reference/cli.mdx
Update okteto delete cli docs to support deletion of multiple contexts.
=> Update okteto delete cli docs

src/content/administration/dashboard.mdx, src/content/self-hosted/install/crds.mdx, src/content/self-hosted/install/releases.mdx, versioned_docs/version-1.14/administration/dashboard.mdx, versioned_docs/version-1.14/self-hosted/install/crds.mdx, versioned_docs/version-1.14/self-hosted/install/releases.mdx
In `1.14.2` we are fixing a bug with custom ports for private registries.
=> 1.14.2 release notes and docs

src/content/self-hosted/guides/okta/index.mdx, src/content/using-dev-envs.mdx, versioned_docs/version-1.10/self-hosted/guides/okta/index.mdx, versioned_docs/version-1.10/using-dev-envs.mdx, versioned_docs/version-1.11/self-hosted/guides/okta/index.mdx, versioned_docs/version-1.11/using-dev-envs.mdx, versioned_docs/version-1.12/self-hosted/guides/okta/index.mdx, versioned_docs/version-1.12/using-dev-envs.mdx, versioned_docs/version-1.13/self-hosted/guides/okta/index.mdx, versioned_docs/version-1.13/using-dev-envs.mdx, versioned_docs/version-1.14/self-hosted/guides/okta/index.mdx, versioned_docs/version-1.14/using-dev-envs.mdx, versioned_docs/version-1.4/self-hosted/guides/okta/index.mdx, versioned_docs/version-1.4/using-dev-envs.mdx, versioned_docs/version-1.5/self-hosted/guides/okta/index.mdx, versioned_docs/version-1.5/using-dev-envs.mdx, versioned_docs/version-1.6/self-hosted/guides/okta/index.mdx, versioned_docs/version-1.6/using-dev-envs.mdx, versioned_docs/version-1.7/self-hosted/guides/okta/index.mdx, versioned_docs/version-1.7/using-dev-envs.mdx, versioned_docs/version-1.8/self-hosted/guides/okta/index.mdx, versioned_docs/version-1.8/using-dev-envs.mdx, versioned_docs/version-1.9/self-hosted/guides/okta/index.mdx, versioned_docs/version-1.9/using-dev-envs.mdx
I believe `every time` is the grammatically correct form? (at least Grammarly keeps marking everytime as wrong)
=> every time vs everytime

src/content/self-hosted/administration/configuration.mdx, src/content/self-hosted/install/upgrade.mdx
Removes PSP docs for next release
Paired with https://github.com/okteto/app/pull/7413
=> Remove PSP

versioned_docs/version-1.14/cloud/custom-domains.mdx
Adding caution that its deprecated for okteto cloud based on  https://community.okteto.com/t/custom-domain-setup/1005
=> Add caution

src/content/self-hosted/install/config.yaml
remove one last reference to cluster.endpoint
=> remove last reference to cluster.endpoint

sidebars.js, src/content/self-hosted/install/diagnostics.mdx, src/content/self-hosted/manage/diagnostics.mdx
Adds documentation for okteto diagnostics. We should GA this until we are OK with the experience.
Pending items:
=> Diagnostics docs

src/content/get-started/preparation.mdx
Adding a note to help SaaS prospects/customers skip unnecessary content.
=> Adding a note about SaaS

src/content/self-hosted/manage/diagnostics.mdx, versioned_docs/version-1.16/self-hosted/manage/diagnostics.mdx
Add krew install instructions to Diagnostics docs
=> Document krew install in diagnostics

src/content/admin/okteto-insights.mdx
Add docs for pod metrics, break apart insights documentation into clearer sections
=> Insights: Add Pod Metrics Documentation

src/content/manifest/okteto-variables.mdx
Merging my content with the content in https://github.com/okteto/docs/pull/578 in this cleaner PR
=> Adding additional content to new 'variables' page

src/content/self-hosted/manage/okteto-license.mdx, src/content/self-hosted/manage/upgrade.mdx, versioned_docs/version-1.13/administration/okteto-license.mdx, versioned_docs/version-1.14/administration/okteto-license.mdx, versioned_docs/version-1.15/administration/okteto-license.mdx, versioned_docs/version-1.16/self-hosted/manage/okteto-license.mdx, versioned_docs/version-1.16/self-hosted/manage/upgrade.mdx
this is my suggestion to make applying for the license more obvious. I think it needs more work though, so feel free to discard or propose better copy
=> add link to upgrade instructions

src/content/release-notes.mdx
Had weird build issues with original 1.17 release branch. I'm starting a new branch to save debugging time. Sorry if you got hit with notification spam
=> add 1.17 release notes to new branch

README.md, src/content/get-started/cloud-provider-guides/aks.mdx, src/content/get-started/cloud-provider-guides/civo.mdx, src/content/get-started/cloud-provider-guides/digitalocean.mdx, src/content/get-started/cloud-provider-guides/eks.mdx, src/content/get-started/cloud-provider-guides/gke.mdx
update navigation on the cloud provider guides so that the 'next' btton takes to to the CLI install guide on all of them
=> update navigation on the cloud provider guides

src/content/manifest/hybrid-development.mdx, versioned_docs/version-1.17/manifest/hybrid-development.mdx
We have two full samples using "hybrid" that we can refer from our docs
=> Adding links for samples using hybrid mode

src/content/release-notes.mdx, versioned_docs/version-1.17/release-notes.mdx
Use features instead of new features to be consistent with the older release notes
=> Use features instead of new features

.prettierrc.json, sidebars.js, src/styles/main.scss
Applying the changes from https://github.com/okteto/docs/pull/611 to main.
The sidebar index is added to:
- Okteto manifest
- Previews
We can add sidebar indexes to more elements, but it probably requires content changes.
We can do that in the following PRs
=> Sidebar index for okteto manifest and previews

sidebars.js, src/content/get-started/cloud-provider-guides/index.mdx
Index sidebar for cloud provider guides to make it eaiser to link to them
=> Index sidebar for cloud installation guides

src/content/reference/helm-chart-values.mdx
As part of the next chart release we will change the default value of this setting. The changes is still not merged but sending PR to not forget about it
=> Changed default value of ingress.forceIngressSubdomain to false

sidebars.js, src/content/index.md
Use indexes to simplify the sidebar of the getting started flow
=> Simplify sidebar for get started flow

src/content/manifest/overview-manifest.mdx
Update doc explaining the okteto manifest to fix some inconsistent definitions, and add an explanation for the "dependencies" section
=> Update okteto manifest overview page

README.md, src/content/self-hosted/manage/upgrade.mdx, src/content/variables.json
Parametrize the chart version using variables
=> Parametrize the chart version

src/content/reference/helm-chart-values.mdx
Creating a new PR to fix conflicts in https://github.com/okteto/docs/pull/469
=> document allowlist for github auth

src/content/core/endpoints/automatic-ssl.mdx, src/content/core/endpoints/private-endpoints.mdx, versioned_docs/version-1.18/core/ingress/automatic-ssl.mdx, versioned_docs/version-1.18/core/ingress/private-endpoints.mdx
Our samples were using an old Ingress syntax that doesn't work on recent Kubernetes versions
=> Update ingress yaml to the new format

src/content/release-notes.mdx, versioned_docs/version-1.18/release-notes.mdx
The RC was created with this change but the release wasn't done yet. I will merge this after the chart release is done
=> Added release notes for 1.18.2 backport

src/content/development/containers/file-sync/aspnetcore.mdx, versioned_docs/version-1.18/guides/samples/aspnetcore.mdx
Signed-off-by: Mario Nevado <nevado.mario@gmail.com>
Regarding to this fix in the repository: https://github.com/okteto/aspnetcore-getting-started/pull/13
=> Added fix of dotnet sample

src/content/development/containers/file-sync/aspnetcore.mdx, versioned_docs/version-1.18/guides/samples/aspnetcore.mdx
Signed-off-by: Mario Nevado <nevado.mario@gmail.com>
=> Update ASPNET to repo changes

src/content/release-notes.mdx
Initial draft of 1.19 release notes - includes CLI
=> add 119 release notes draft

src/content/core/okteto-variables.mdx, versioned_docs/version-1.19/core/okteto-variables.mdx
A couple of customers are asking for this, so I'd like to have a link to send for this
=> Document the OKTETO_IS_PREVIEW_ENVIRONMENT environment variable

src/content/self-hosted/helm-configuration.mdx
=> Revert "Documentation for custom Node Selectors"

src/content/reference/okteto-cli.mdx
Add documentation of an example on how to use `okteto up --command`
=> docs: add documentation for okteto up command

src/content/self-hosted/helm-configuration.mdx
=> Add Documentation for custom Node Selectors after 1.20 release

src/content/previews/index.mdx, src/content/previews/using-github-actions.mdx, src/content/previews/using-gitlab-cicd.mdx
There was no description in the spec about what this should look like. Not sure if this is enough, or what else we want to add and how. @pchico83 @codyjlandstrom can you please review?
=> Add test to preview environment docs

sidebars.js, src/content/testing/getting-started-test.mdx, src/content/testing/getting-started.mdx, src/content/testing/index.mdx, src/styles/main.scss
Draft version of the getting started with Okteto Test guide
=> Getting started with Okteto Test

src/content/release-notes.mdx, versioned_docs/version-1.21/release-notes.mdx
Added patch version for `1.21` release notes title to be consistent with previous ones
=> Added patch version to 1.21 release notest to be consistent with the previous ones

versioned_docs/version-1.20/self-hosted/install/auth/okta.mdx
=> Remove inaccurate reference to okteto secrets

src/content/previews/using-github-actions.mdx, versioned_docs/version-1.20/previews/using-github-actions.mdx, versioned_docs/version-1.20/self-hosted/install/auth/okta.mdx, versioned_docs/version-1.21/previews/using-github-actions.mdx
A customer was setting the wrong value here, I think a clear example can help guide
=> add example for OKTETO_CONTEXT

src/content/release-notes.mdx, versioned_docs/version-1.21/release-notes.mdx
Added release notes for version `1.21.1` which will be released later today. There are the 2 bug fixes included
=> Added release notes for 1.21.1 version

src/content/self-hosted/helm-configuration.mdx, versioned_docs/version-1.21/self-hosted/helm-configuration.mdx
Added documentation for flag `namespace.autoRoleBinding.enabled`
=> Added documentation for setting autoRoleBinding

src/content/reference/okteto-cli.mdx, versioned_docs/version-1.21/reference/okteto-cli.mdx, versioned_docs/version-1.22/reference/okteto-cli.mdx
Basically provide some more info to _why_ one might want to disable the caching.
=> Clarify okteto test --no-cache option

src/content/self-hosted/manage/upgrade.mdx, versioned_docs/version-1.22/self-hosted/manage/upgrade.mdx
I am proposing to add a paragraph going a bit deeper showing an example on how to deal with potential issues caused by the removal of this feature
=> add example to fix role-binding issue with cluster-admin role

src/content/development/containers/file-sync/java.mdx, versioned_docs/version-1.22/development/containers/file-sync/java.mdx
=> update java guide to be more concise

src/content/development/containers/file-sync/java.mdx, versioned_docs/version-1.22/development/containers/file-sync/java.mdx
=> Clarification on including spring-boot-devtools in sample

src/content/self-hosted/helm-configuration.mdx, versioned_docs/version-1.15/self-hosted/administration/configuration.mdx, versioned_docs/version-1.16/reference/helm-chart-values.mdx, versioned_docs/version-1.17/reference/helm-chart-values.mdx, versioned_docs/version-1.18/reference/helm-chart-values.mdx, versioned_docs/version-1.19/self-hosted/helm-configuration.mdx, versioned_docs/version-1.20/self-hosted/helm-configuration.mdx, versioned_docs/version-1.21/self-hosted/helm-configuration.mdx, versioned_docs/version-1.22/self-hosted/helm-configuration.mdx
I removed it in the last 8 versions as it was removed some time ago
=> Removed prepullImages setting in several versions as it is not used anymore

src/content/release-notes.mdx, src/content/testing/index.mdx, versioned_docs/version-1.21/release-notes.mdx, versioned_docs/version-1.22/release-notes.mdx, versioned_docs/version-1.23/release-notes.mdx
=> Added release notes for release 1.23.1

netlify.toml, versioned_docs/version-1.12/reference/cli.mdx, versioned_docs/version-1.13/reference/cli.mdx, versioned_docs/version-1.14/reference/cli.mdx, versioned_docs/version-1.15/reference/cli.mdx, versioned_docs/version-1.16/deploy/deploy-from-git.mdx
Some redirects that were missing from the first pass in https://github.com/okteto/docs/pull/803
=> Add redirects

src/content/self-hosted/install/auth/index.mdx, src/content/self-hosted/install/auth/token.mdx
We will iterate the content more and add screenshots once the feature is ready, but sending an initial PR.
One of the reasons is to have a final link to document how to retrieve a User Token using `kubectl`, which will be pointed from the UI
=> Initial docs for multi user

src/content/self-hosted/helm-configuration.mdx
Add docs for the event exporter competent deployed with Okteto Insights
=> Event Exporter documentation

src/content/release-notes.mdx, versioned_docs/version-1.23/release-notes.mdx, versioned_docs/version-1.24/release-notes.mdx
Added release notes for the patch versions created for `1.23` and `1.24`
=> Added release notes for 1.23.3 and 1.24.1 versions

src/content/reference/docker-compose.mdx, src/content/reference/okteto-manifest.mdx
Changes to adapt to Okteto CLI 3.0:
https://www.okteto.com/blog/cli-three-release/
=> Docker Compose and Okteto Manifest changes for CLI 3.0

src/content/reference/okteto-cli.mdx
=> Add documentation for running tests with okteto test command

src/content/core/okteto-manifest.mdx, src/content/reference/feature-flags.mdx, src/content/reference/okteto-cli.mdx, src/content/reference/okteto-manifest.mdx
=> fix (docs): typos on the documentation

sidebars.js, src/content/admin/cloud-credentials/aws.mdx, src/content/admin/cloud-credentials/gcp.mdx, src/content/admin/cloud-credentials/index.mdx
Add sidebar for cloud credentials docs
=> Add Cloud Credentials to the sidebar

src/content/reference/okteto-manifest.mdx
Explain a little bit the lifecycle functionality
Adds lifecycle extended notation
=> Refactor lifecycle hooks configuration in okteto-manifest.mdx

sidebars.js, src/content/get-started/install/openshift.mdx
This PR adds an installation guide for OpenShift
=> Installation guide for OpenShift

src/content/admin/okteto-insights.mdx, src/content/core/okteto-variables.mdx
Also, fixing style in the "Okteto Variables" doc
=> Document recommended "scrape_timeout" in Prometheus

src/content/reference/okteto-manifest.mdx
Implemented on this PR: https://github.com/okteto/okteto/pull/4513
=> Document "priorityClassName" for dev containers

src/content/admin/cleanup.mdx
In this PR and updating our terminology related to the GC to be more consistent:
- Resource Cleanup -> Garbage Collector
- Inactivity period -> Sleep period
- Deletion Period -> Delete Period
Garbage Collector, Sleep period, and Delete Period are what are used in the product today. I think it's better to standardize on these terms since modifying the product is more time consuming
=> Use consistent terminology for the Garbage Collector

src/content/self-hosted/helm-configuration.mdx
This reverts commit cd30083963f18063b8162f0f887206f52b37307e.
=> Revert "Add `resourceManager` helm config (#834)"

sidebars.js, src/content/get-started/deploy-your-app/build.mdx, src/content/self-hosted/manage/buildkit-high-performance.mdx
Documenting the setup we are using in SaaS to have optimal build performance
=> Guide to configure buildkit for high performance

src/content/index.md, src/content/reference/supported-github-actions.mdx, versioned_docs/version-1.25/index.md, versioned_docs/version-1.25/reference/supported-github-actions.mdx
"Okteto Test" is not listed in our official test actions
=> Document "Okteto Test" as an official Okteto GH Action

src/content/self-hosted/manage/buildkit-high-performance.mdx
Dument how to expose buildkit on a dedicated LB as a best practice
=> Document how to expose BuildKit on a dedicated LB

src/content/testing/getting-started-test.mdx, versioned_docs/version-1.21/testing/getting-started-test.mdx, versioned_docs/version-1.22/testing/getting-started-test.mdx, versioned_docs/version-1.23/testing/getting-started-test.mdx, versioned_docs/version-1.24/testing/getting-started-test.mdx, versioned_docs/version-1.25/testing/getting-started-test.mdx
Fix a typo in the okteto test section
=> fix: context for okteto test api

src/content/self-hosted/helm-configuration.mdx
This PR documents how to migrate an existing defaultBackend.
=> Document migration steps for defaultBackend

sidebars.js, src/content/self-hosted/install/auth/azure-ad.mdx, src/content/self-hosted/install/auth/gitlab.mdx, src/content/self-hosted/install/auth/okta.mdx
Making note of the character limitations for the email field when creating new users.
Side note - We don't have a docs page for adding users. (should we add one?)
=> Note email character limitation

src/content/self-hosted/helm-configuration.mdx
The Okteto chart has these 2 dependencies that are not mentioned yet
=> add redis and reloader chart dependencies

src/content/self-hosted/helm-configuration.mdx
Superseded by Catalog feature several versions ago.
=> Remove quickstarts documentation

src/content/admin/resource-manager.mdx
This PR addresses the following:
1. Rephrase 'Rolling Back Changes` to 'Exclude Resources'
2. Adding samples
=> [Resource Manager] Improve docs and add examples

src/content/release-notes.mdx, versioned_docs/version-1.26/release-notes.mdx
Not sure why but the header is not rendering correctly, perhaps some encoding issue with the spacing.
=> fix 1.26.1 header

src/content/release-notes.mdx, versioned_docs/version-1.23/release-notes.mdx, versioned_docs/version-1.24/release-notes.mdx, versioned_docs/version-1.25/release-notes.mdx, versioned_docs/version-1.26/release-notes.mdx
Fixing a typo that we have been repeating since a few versions: "This versions".
=> fix this version plural

src/content/self-hosted/helm-configuration.mdx, versioned_docs/version-1.26/self-hosted/helm-configuration.mdx
Added the section for the sshAgent new component starting to be deployed on `1.26`.
=> Added documentation for the ssh-component in the helm configuration settings page

src/content/reference/okteto-manifest.mdx
=> dev.environment can also be a list

src/content/admin/cloud-credentials/index.mdx, src/content/admin/registry-credentials/index.mdx
Adding notes in visible sections of the docs in case users are searching for why they can't edit
=> Add notes about the new Read-only Tags

README.md, src/content/self-hosted/manage/air-gapped.mdx, src/content/variables.json, versioned_docs/version-1.27/self-hosted/manage/air-gapped.mdx
Incorporate the last improvements in the airgap installation guide, and document how to download the synching binary
=> Updates the airgap installation guide

versioned_docs/version-1.27/self-hosted/manage/air-gapped.mdx
Update air-gapped sidebar to match 1.28
=> Update air-gapped sidebar

src/content/admin/cleanup.mdx
Added a clarification in the delete period description to indicate the difference when the sleep period is enabled or not
=> Added a clarification about the delete period of the GC settings

src/content/self-hosted/helm-configuration.mdx
Mention the key for registry.storage for 'completeness' sake and to aid with discoverability
=> Update helm-configuration.mdx to include registry.storage

src/content/release-notes.mdx, src/content/variables.json, versioned_docs/version-1.27/release-notes.mdx, versioned_docs/version-1.27/variables.json
=> bummp chart version

src/content/get-started/install/index.mdx, src/content/self-hosted/manage/air-gapped.mdx
@rlamana Could you verify that these are the versions that we want to support?
- **Google Chrome**: Latest 2 major versions
- **Mozilla Firefox**: Latest 2 major versions
- **Microsoft Edge**: Latest 2 major versions
- **Safari**: Latest 2 major versions (macOS only)
=> Add notes on browser compatibility

src/content/get-started/install/index.mdx
Re: [DEV-745](https://okteto.atlassian.net/browse/DEV-745)
Follow-up on #972 
Adds a note to clarify that we do not support mobile browsers
[DEV-745]: https://okteto.atlassian.net/browse/DEV-745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add a note for mobile browsers not being supported

netlify.toml
Using regex in the redirect file didn't work for some reason. Rolling back for now
=> Rollback changes in redirect file

src/content/reference/okteto-manifest.mdx, versioned_docs/version-1.30/reference/okteto-manifest.mdx
This PR explicitly mentions the `nginx` driver
=> Update the "divert" terminology

src/content/release-notes.mdx, versioned_docs/version-1.30/release-notes.mdx
Added release notes for the upcoming patch for `1.30` release
=> Release notes for 1.30.1

src/content/index.md
Make some stylistic updates and prep for BYOC
=> Make updates to the docs landing page

src/content/admin/okteto-insights.mdx, src/content/admin/resource-manager.mdx, versioned_docs/version-1.20/admin/okteto-insights.mdx, versioned_docs/version-1.21/admin/okteto-insights.mdx, versioned_docs/version-1.22/admin/okteto-insights.mdx, versioned_docs/version-1.23/admin/okteto-insights.mdx, versioned_docs/version-1.24/admin/okteto-insights.mdx, versioned_docs/version-1.25/admin/okteto-insights.mdx, versioned_docs/version-1.25/admin/resource-manager.mdx, versioned_docs/version-1.26/admin/okteto-insights.mdx, versioned_docs/version-1.26/admin/resource-manager.mdx, versioned_docs/version-1.27/admin/okteto-insights.mdx, versioned_docs/version-1.27/admin/resource-manager.mdx, versioned_docs/version-1.28/admin/okteto-insights.mdx, versioned_docs/version-1.28/admin/resource-manager.mdx, versioned_docs/version-1.29/admin/okteto-insights.mdx, versioned_docs/version-1.29/admin/resource-manager.mdx, versioned_docs/version-1.30/admin/okteto-insights.mdx, versioned_docs/version-1.30/admin/resource-manager.mdx, versioned_docs/version-1.31/admin/okteto-insights.mdx, versioned_docs/version-1.31/admin/resource-manager.mdx
- Added mention of metrics server to Okteto Insights setup page
- Added link to Kubernetes Metric Server documentation on Okteto Insights, and Resource Manager documentation.
=> Add mention of metrics server to Okteto Insights setup

src/content/reference/docker-compose.mdx, versioned_docs/version-1.27/reference/docker-compose.mdx, versioned_docs/version-1.28/reference/docker-compose.mdx, versioned_docs/version-1.29/reference/docker-compose.mdx, versioned_docs/version-1.30/reference/docker-compose.mdx, versioned_docs/version-1.31/reference/docker-compose.mdx, versioned_docs/version-1.32/reference/docker-compose.mdx
@jpf-okteto If this looks good to you, I'll go ahead and add to previous supported versions as well
=> add docker compose comparison guide

src/content/byoc/gcp/index.mdx, versioned_docs/version-1.33/byoc/gcp/index.mdx
https://okteto.slack.com/archives/C044HDNUE6A/p1750758934913909
=> Fix SA role for BYOC for GCP

src/content/release-notes.mdx, versioned_docs/version-1.35/release-notes.mdx
The official release is on their way, so sending the docs PR to have it ready
=> Added release notes for 1.35.1 release

.vscode/settings.json, src/content/admin/cleanup.mdx, src/content/admin/dashboard.mdx, src/content/core/namespaces.mdx
- Restructured cleanup guide with better section organization
- Made "What Counts as Activity" a prominent top-level section
- Added comprehensive configuration examples and troubleshooting
- Improved manual sleep/wake instructions with step-by-step guides
- Added best practices section with team-size recommendations
=> Improve garbage collection documentation structure and clarity

src/content/release-notes.mdx, versioned_docs/version-1.35/release-notes.mdx
Created release notes for the ongoing `1.35.2` patch version
=> Add release notes for 1.35.2 version

src/content/admin/okteto-api.mdx
@ifbyol Adding a quick mention in the API docs that the user delete operation is available.
Let me know if there is anything else that should be added
=> Add the delete operation under the users endpoint

src/content/self-hosted/helm-configuration.mdx
Document the new settings for Redis after removing the dependency on bitnami redis helm chart
=> Document the new "redis" helm section

src/content/reference/docker-compose.mdx
Add documentation for new supported compose property endpoint_mode introduced at:
- https://github.com/okteto/okteto/pull/4783
=> docs: add endpoint_mode

Dockerfile, README.md, package.json, src/tutorials/optimize-your-development-environment.mdx
fixing broken link in tutorial that's blocking the build
=> fix broken build
